########################################################################################
[TabelaTipoDeMarcacaoP8_TPMARCA]
__DFV__=
?=1E#1a. Entrada
?=1S#1a. Saida
?=2E#2a. Entrada
?=2S#2a. Saida
?=3E#3a. Entrada
?=3S#3a. Saida
?=4E#4a. Entrada
?=4S#4a. Saida
?=5E#5a. Entrada
?=5S#5a. Saida
?=6E#6a. Entrada
?=6S#6a. Saida