########################################################################################
[TabelaVerbasSRVFOL]
__DFV__=
#################################################################################################################################
#Eventos Customizados FOL
#################################################################################################################################
512=512#INSS SOBRE 13O SALARIO => 13O SALARIO ADIANTAMENTO DESC
563=563#IRF (13O SALARIO) => 13O SALARIO ADIANTAMENTO DESC
565=565#IRF (13O SALARIO) => 13O SALARIO ADIANTAMENTO DESC
