#include "totvs.ch"
#include "fileio.ch"
#include "parmtype.ch"
#include "jsonarray.ch"

using namespace dna.tech

procedure u_fileIOPF()
    __cInternet:=nil
    u_fileIOPerform()
return

procedure u_fileIOPerform()
    __cInternet:=nil
    FWMsgRun(nil,{||__fileIOPerform()},"fileIOPerform","Aguarde...")
return

static procedure __fileIOPerform()

    local aFiles:={;
        {"\datasul2protheus\tables\funcionario.csv",.T.,.T.,3605801};
       ,{"C:\GitHub\naldodj-DataSul2TotvsProtheus\datasul2Protheus\tables\funcionario.csv",.T.,.T.,3605801};
       ,{"\datasul2protheus\tablesdefinition\fulltablesdefinition.txt",.F.,.T.,3636546};
       ,{"C:\GitHub\naldodj-DataSul2TotvsProtheus\datasul2Protheus\tablesdefinition\fulltablesdefinition.txt",.F.,.T.,3636546};
       ,{"\datasul2protheus\tables\movto_calcul_func.csv",.F.,.T.,14574748};
       ,{"C:\GitHub\naldodj-DataSul2TotvsProtheus\datasul2Protheus\tables\movto_calcul_func.csv",.F.,.T.,14574748};
       ,{"\datasul2protheus\tables\marcac_ptoelet.csv",.F.,.T.,18908930};
       ,{"C:\GitHub\naldodj-DataSul2TotvsProtheus\datasul2Protheus\tables\marcac_ptoelet.csv",.F.,.T.,18908930};
    } as array

    local aPerform as array
    local aProperties as array

    local cLine as character
    local cFile as character
    local cPerform as character
    local cProperty as character
    local cFileReader as character

    local jPerform as json

    local lStrHashLog:=.F. as logical
    local lDecodeUTF8:=.F. as logical
    local lSequential:=.F. as logical

    local nFile as numeric

    local oPerform as object

    local i,j,k as numeric

    //Call: 0-Not Call,1=Sequential,2=Not Sequential,3=Both
    beginContent var cPerform
{
     "TFILEREAD"            :  {"Reader":"","RDD":""          ,"Call":3,"TimeProcStart":"","TimeProcEnd":"","ProcStart":0,"ProcEnd":0,"PartialTimeProc":0,"TotalTimeProc":0,"PartialTimeReader":0,"TotalTimeReader":0,"PartialStrTokArr":0,"PartialStrTokArr2":0,"Partial__StrTokArray":0,"TotalStrTokArr":0,"TotalStrTokArr2":0,"Total__StrTokArray":0,"PartialTimeStrTokArr":0,"PartialTimeStrTokArr2":0,"PartialTime__StrTokArray":0,"TotalTimeStrTokArr":0,"TotalTimeStrTokArr2":0,"TotalTime__StrTokArray":0,"Lines":0,"TotalLinesRead":0,"FileSize":0,"TotalBytesRead":0,"StrHash":0,"PartialTimeStrHash":0,"TotalTimeStrHash":0,"TimeOutThresHold":0,"IsDisqualifiedByTimeOut":false,"PartialTimeIsDisqualifiedVerify":0,"TotalTimeIsDisqualifiedVerify":0}
    ,"FWFILEREADER"         :  {"Reader":"","RDD":""          ,"Call":3,"TimeProcStart":"","TimeProcEnd":"","ProcStart":0,"ProcEnd":0,"PartialTimeProc":0,"TotalTimeProc":0,"PartialTimeReader":0,"TotalTimeReader":0,"PartialStrTokArr":0,"PartialStrTokArr2":0,"Partial__StrTokArray":0,"TotalStrTokArr":0,"TotalStrTokArr2":0,"Total__StrTokArray":0,"PartialTimeStrTokArr":0,"PartialTimeStrTokArr2":0,"PartialTime__StrTokArray":0,"TotalTimeStrTokArr":0,"TotalTimeStrTokArr2":0,"TotalTime__StrTokArray":0,"Lines":0,"TotalLinesRead":0,"FileSize":0,"TotalBytesRead":0,"StrHash":0,"PartialTimeStrHash":0,"TotalTimeStrHash":0,"TimeOutThresHold":0,"IsDisqualifiedByTimeOut":false,"PartialTimeIsDisqualifiedVerify":0,"TotalTimeIsDisqualifiedVerify":0}
    ,"FILEREADER_FILE"      :  {"Reader":"","RDD":"FILE"      ,"Call":3,"TimeProcStart":"","TimeProcEnd":"","ProcStart":0,"ProcEnd":0,"PartialTimeProc":0,"TotalTimeProc":0,"PartialTimeReader":0,"TotalTimeReader":0,"PartialStrTokArr":0,"PartialStrTokArr2":0,"Partial__StrTokArray":0,"TotalStrTokArr":0,"TotalStrTokArr2":0,"Total__StrTokArray":0,"PartialTimeStrTokArr":0,"PartialTimeStrTokArr2":0,"PartialTime__StrTokArray":0,"TotalTimeStrTokArr":0,"TotalTimeStrTokArr2":0,"TotalTime__StrTokArray":0,"Lines":0,"TotalLinesRead":0,"FileSize":0,"TotalBytesRead":0,"StrHash":0,"PartialTimeStrHash":0,"TotalTimeStrHash":0,"TimeOutThresHold":0,"IsDisqualifiedByTimeOut":false,"PartialTimeIsDisqualifiedVerify":0,"TotalTimeIsDisqualifiedVerify":0}
    ,"FILEREADER_HASHMAP"   :  {"Reader":"","RDD":"HASHMAP"   ,"Call":3,"TimeProcStart":"","TimeProcEnd":"","ProcStart":0,"ProcEnd":0,"PartialTimeProc":0,"TotalTimeProc":0,"PartialTimeReader":0,"TotalTimeReader":0,"PartialStrTokArr":0,"PartialStrTokArr2":0,"Partial__StrTokArray":0,"TotalStrTokArr":0,"TotalStrTokArr2":0,"Total__StrTokArray":0,"PartialTimeStrTokArr":0,"PartialTimeStrTokArr2":0,"PartialTime__StrTokArray":0,"TotalTimeStrTokArr":0,"TotalTimeStrTokArr2":0,"TotalTime__StrTokArray":0,"Lines":0,"TotalLinesRead":0,"FileSize":0,"TotalBytesRead":0,"StrHash":0,"PartialTimeStrHash":0,"TotalTimeStrHash":0,"TimeOutThresHold":0,"IsDisqualifiedByTimeOut":false,"PartialTimeIsDisqualifiedVerify":0,"TotalTimeIsDisqualifiedVerify":0}
    ,"FILEREADER_SQLITE_MEM":  {"Reader":"","RDD":"SQLITE_MEM","Call":3,"TimeProcStart":"","TimeProcEnd":"","ProcStart":0,"ProcEnd":0,"PartialTimeProc":0,"TotalTimeProc":0,"PartialTimeReader":0,"TotalTimeReader":0,"PartialStrTokArr":0,"PartialStrTokArr2":0,"Partial__StrTokArray":0,"TotalStrTokArr":0,"TotalStrTokArr2":0,"Total__StrTokArray":0,"PartialTimeStrTokArr":0,"PartialTimeStrTokArr2":0,"PartialTime__StrTokArray":0,"TotalTimeStrTokArr":0,"TotalTimeStrTokArr2":0,"TotalTime__StrTokArray":0,"Lines":0,"TotalLinesRead":0,"FileSize":0,"TotalBytesRead":0,"StrHash":0,"PartialTimeStrHash":0,"TotalTimeStrHash":0,"TimeOutThresHold":0,"IsDisqualifiedByTimeOut":false,"PartialTimeIsDisqualifiedVerify":0,"TotalTimeIsDisqualifiedVerify":0}
    ,"FILEREADER_SQLITE_TMP":  {"Reader":"","RDD":"SQLITE_TMP","Call":3,"TimeProcStart":"","TimeProcEnd":"","ProcStart":0,"ProcEnd":0,"PartialTimeProc":0,"TotalTimeProc":0,"PartialTimeReader":0,"TotalTimeReader":0,"PartialStrTokArr":0,"PartialStrTokArr2":0,"Partial__StrTokArray":0,"TotalStrTokArr":0,"TotalStrTokArr2":0,"Total__StrTokArray":0,"PartialTimeStrTokArr":0,"PartialTimeStrTokArr2":0,"PartialTime__StrTokArray":0,"TotalTimeStrTokArr":0,"TotalTimeStrTokArr2":0,"TotalTime__StrTokArray":0,"Lines":0,"TotalLinesRead":0,"FileSize":0,"TotalBytesRead":0,"StrHash":0,"PartialTimeStrHash":0,"TotalTimeStrHash":0,"TimeOutThresHold":0,"IsDisqualifiedByTimeOut":false,"PartialTimeIsDisqualifiedVerify":0,"TotalTimeIsDisqualifiedVerify":0}
    ,"FILEREADER_TOPCONN"   :  {"Reader":"","RDD":"TOPCONN"   ,"Call":3,"TimeProcStart":"","TimeProcEnd":"","ProcStart":0,"ProcEnd":0,"PartialTimeProc":0,"TotalTimeProc":0,"PartialTimeReader":0,"TotalTimeReader":0,"PartialStrTokArr":0,"PartialStrTokArr2":0,"Partial__StrTokArray":0,"TotalStrTokArr":0,"TotalStrTokArr2":0,"Total__StrTokArray":0,"PartialTimeStrTokArr":0,"PartialTimeStrTokArr2":0,"PartialTime__StrTokArray":0,"TotalTimeStrTokArr":0,"TotalTimeStrTokArr2":0,"TotalTime__StrTokArray":0,"Lines":0,"TotalLinesRead":0,"FileSize":0,"TotalBytesRead":0,"StrHash":0,"PartialTimeStrHash":0,"TotalTimeStrHash":0,"TimeOutThresHold":0,"IsDisqualifiedByTimeOut":false,"PartialTimeIsDisqualifiedVerify":0,"TotalTimeIsDisqualifiedVerify":0}
    ,"FT"                   :  {"Reader":"","RDD":""          ,"Call":3,"TimeProcStart":"","TimeProcEnd":"","ProcStart":0,"ProcEnd":0,"PartialTimeProc":0,"TotalTimeProc":0,"PartialTimeReader":0,"TotalTimeReader":0,"PartialStrTokArr":0,"PartialStrTokArr2":0,"Partial__StrTokArray":0,"TotalStrTokArr":0,"TotalStrTokArr2":0,"Total__StrTokArray":0,"PartialTimeStrTokArr":0,"PartialTimeStrTokArr2":0,"PartialTime__StrTokArray":0,"TotalTimeStrTokArr":0,"TotalTimeStrTokArr2":0,"TotalTime__StrTokArray":0,"Lines":0,"TotalLinesRead":0,"FileSize":0,"TotalBytesRead":0,"StrHash":0,"PartialTimeStrHash":0,"TotalTimeStrHash":0,"TimeOutThresHold":0,"IsDisqualifiedByTimeOut":false,"PartialTimeIsDisqualifiedVerify":0,"TotalTimeIsDisqualifiedVerify":0}
}
    endContent

    //Uso JSONArray para dar suporte a JSONObject do protheus.
    //Ele se perde ao renderizar o JSON acima
    //Uma outra solução é:
    //Criar o Objeto JSON à partir de JSONSerialize
    //jPerform:=JSONSerialize("{}")
    //Renderizar normalmente
    //jPerform:FromJSON(cPerform)
    //O problema ocorre apenas 1 vez.
    //Após usar esta solução (jPerform:=JSONSerialize("{}")) e até que se reinicie o appserver o problema não mais ocorre.
    oPerform:=JSONArray():New()
    oPerform:FromJSON(cPerform)

    jPerform:=JSONObject():New()
    aPerform:=oPerform:GetNames()
    for i:=1 to Len(aPerform)
        cFileReader:=aPerform[i]
        jPerform[cFileReader]:=JSONObject():New()
        aProperties:=oPerform[#cFileReader]:GetNames()
        for j:=1 to Len(aProperties)
            cProperty:=aProperties[j]
            jPerform[cFileReader][cProperty]:=oPerform[#cFileReader][#cProperty]
        next j
    next i

    //Bye Bye JSONArray. Obrigado pelo Suporte!
    FreeObj(@oPerform)

    for nFile:=1 to Len(aFiles)
        if (!aFiles[nFile][3])
            loop
        endif
        cLine:=""
        cFile:=aFiles[nFile][1]
        lDecodeUTF8:=aFiles[nFile][2]
        for k:=1 to 2
            lSequential:=(k==1)
            ConOut("FileName["+cFile+"] "+if(!lSequential,"Not ","")+"Sequential reading")
            for i:=1 to Len(aPerform)
                cFileReader:=aPerform[i]
                jPerform[cFileReader]["Reader"]:=cFileReader
                jPerform[cFileReader]["Lines"]:=0
                jPerform[cFileReader]["PartialStrTokArr"]:=0
                jPerform[cFileReader]["PartialTimeStrTokArr"]:=0
                jPerform[cFileReader]["PartialStrTokArr2"]:=0
                jPerform[cFileReader]["PartialTimeStrTokArr2"]:=0
                jPerform[cFileReader]["Partial__StrTokArray"]:=0
                jPerform[cFileReader]["PartialTime__StrTokArray"]:=0
                jPerform[cFileReader]["StrHash"]:=0
                jPerform[cFileReader]["PartialTimeStrHash"]:=0
                jPerform[cFileReader]["TimeOutThresHold"]:=aFiles[nFile][4]
                jPerform[cFileReader]["IsDisqualifiedByTimeOut"]:=.F.
                jPerform[cFileReader]["PartialTimeIsDisqualifiedVerify"]:=0
                if (lStrHashLog)
                    jPerform[cFileReader]["StrHashLogger"]:=FileLogger():New(cFile+"."+cFileReader+"."+UUIDRandomSeq()+".log")
                endif
                jPerform[cFileReader]["FileSize"]:=0
                //Call: 0-Not Call,1=Sequential,2=Not Sequential,3=Both
                if (NTools():ContainN(3,jPerform[cFileReader]["Call"]))
                    if (cFileReader=="FT")
                        __TST_FT(cFile,jPerform[cFileReader],lStrHashLog,lSequential,lDecodeUTF8)
                    elseif (cFileReader=="FWFILEREADER")
                        __TST_FWFILEREADER(cFile,jPerform[cFileReader],lStrHashLog,lSequential,lDecodeUTF8)
                    elseif (cFileReader=="TFILEREAD")
                        __TST_TFILEREAD(cFile,jPerform[cFileReader],lStrHashLog,lSequential,lDecodeUTF8)
                    else
                        __TST_FILEREADER(cFile,jPerform[cFileReader],lStrHashLog,lSequential,lDecodeUTF8)
                    endif
                endif
            next k
        next i
        ConOut(Replicate("*",550))
    next nFile

    for i:=1 to Len(aPerform)
        cFileReader:=aPerform[i]
        ConOut(cFileReader+" => ElapTimeReaderTotal["+__MiliSecondsToTime(jPerform[cFileReader]["TotalTimeReader"])+"]")
    next i

    FWFreeArray(@aFiles)
    FWFreeArray(@aPerform)

    FreeObj(@jPerform)

return

static procedure __TSTStrTokArray(cLine as character,jPerformReader as json)

    local aLine as array

    local nStrTokTime as numeric

    *****************************************************************
    nStrTokTime:=TimeCounter()
        aLine:=StrTokArr(cLine,";")
    jPerformReader["PartialTimeStrTokArr"]+=(TimeCounter()-nStrTokTime)
    jPerformReader["PartialStrTokArr"]+=Len(aLine)
    *****************************************************************
    FWFreeArray(@aLine)
    *****************************************************************
    nStrTokTime:=TimeCounter()
        aLine:=StrTokArr2(cLine,";",.T.)
    jPerformReader["PartialTimeStrTokArr2"]+=(TimeCounter()-nStrTokTime)
    jPerformReader["PartialStrTokArr2"]+=Len(aLine)
    *****************************************************************
    FWFreeArray(@aLine)
    *****************************************************************
    nStrTokTime:=TimeCounter()
        aLine:=cTools():__StrTokArray(cLine,";")
    jPerformReader["PartialTime__StrTokArray"]+=(TimeCounter()-nStrTokTime)
    jPerformReader["Partial__StrTokArray"]+=Len(aLine)
    *****************************************************************
    FWFreeArray(@aLine)
    *****************************************************************

return

static procedure __StrHash(cStr,jPerformReader,lStrHashLog)
    local nStrHash as numeric
    local nPartialTimeStrHash:=TimeCounter() as numeric
    nStrHash:=cTools():StrHash(cStr)
    jPerformReader["StrHash"]+=nStrHash
    if (lStrHashLog)
        jPerformReader["StrHashLogger"]:WriteLine(StrZero(nStrHash,16)+" "+cStr)
    endif
    jPerformReader["PartialTimeStrHash"]+=(TimeCounter()-nPartialTimeStrHash)
return

static procedure __ConOut(jPerformReader as json,lStrHashLog as logical)

    local jPerformReaderOut as json

    jPerformReader["PartialTimeProc"]:=(jPerformReader["ProcEnd"]-jPerformReader["ProcStart"])
    jPerformReader["PartialTimeReader"]:=(;
        jPerformReader["PartialTimeProc"]-(;
            jPerformReader["PartialTimeStrTokArr"];
           +jPerformReader["PartialTimeStrTokArr2"];
           +jPerformReader["PartialTime__StrTokArray"];
           +jPerformReader["PartialTimeStrHash"];
           +jPerformReader["PartialTimeIsDisqualifiedVerify"];
        );
    )

    jPerformReader["TotalTimeProc"]+=jPerformReader["PartialTimeProc"]
    jPerformReader["TotalTimeReader"]+=jPerformReader["PartialTimeReader"]
    jPerformReader["TotalTimeStrTokArr"]+=jPerformReader["PartialTimeStrTokArr"]
    jPerformReader["TotalTimeStrTokArr2"]+=jPerformReader["PartialTimeStrTokArr2"]
    jPerformReader["TotalTime__StrTokArray"]+=jPerformReader["PartialTime__StrTokArray"]

    jPerformReader["TotalStrTokArr"]+=jPerformReader["PartialStrTokArr"]
    jPerformReader["TotalStrTokArr2"]+=jPerformReader["PartialStrTokArr2"]
    jPerformReader["Total__StrTokArray"]+=jPerformReader["Partial__StrTokArray"]

    jPerformReader["TotalLinesRead"]+=jPerformReader["Lines"]
    jPerformReader["TotalBytesRead"]+=jPerformReader["FileSize"]

    jPerformReader["TotalTimeStrHash"]+=jPerformReader["PartialTimeStrHash"]

    jPerformReader["TotalTimeIsDisqualifiedVerify"]+=jPerformReader["PartialTimeIsDisqualifiedVerify"]

    if (lStrHashLog)
        jPerformReader["StrHashLogger"]:Close()
        FreeObj(@jPerformReader["StrHashLogger"])
        jPerform:DelName("StrHashLogger")
    endif

    jPerformReaderOut:=JSONObjectClone():CloneJSON(jPerformReader)

    jPerformReaderOut["Reader"]:=PadR(jPerformReaderOut["Reader"],21)
    jPerformReaderOut["RDD"]:=PadR(jPerformReaderOut["RDD"],10)

    jPerformReaderOut["TotalTimeProc"]:=__MiliSecondsToTime(jPerformReaderOut["TotalTimeProc"])
    jPerformReaderOut["PartialTimeProc"]:=__MiliSecondsToTime(jPerformReaderOut["PartialTimeProc"])

    jPerformReaderOut["TotalTimeReader"]:=__MiliSecondsToTime(jPerformReaderOut["TotalTimeReader"])
    jPerformReaderOut["PartialTimeReader"]:=__MiliSecondsToTime(jPerformReaderOut["PartialTimeReader"])

    jPerformReaderOut["TotalTimeStrTokArr"]+=jPerformReaderOut["PartialTimeStrTokArr"]
    jPerformReaderOut["PartialTimeStrTokArr"]:=__MiliSecondsToTime(jPerformReaderOut["PartialTimeStrTokArr"])

    jPerformReaderOut["TotalTimeStrTokArr2"]+=jPerformReaderOut["PartialTimeStrTokArr2"]
    jPerformReaderOut["PartialTimeStrTokArr2"]:=__MiliSecondsToTime(jPerformReaderOut["PartialTimeStrTokArr2"])

    jPerformReaderOut["TotalTime__StrTokArray"]+=jPerformReaderOut["PartialTime__StrTokArray"]
    jPerformReaderOut["PartialTime__StrTokArray"]:=__MiliSecondsToTime(jPerformReaderOut["PartialTime__StrTokArray"])

    jPerformReaderOut["TotalTimeStrHash"]:=__MiliSecondsToTime(jPerformReaderOut["TotalTimeStrHash"])
    jPerformReaderOut["PartialTimeStrHash"]:=__MiliSecondsToTime(jPerformReaderOut["PartialTimeStrHash"])

    jPerformReaderOut["TotalTimeIsDisqualifiedVerify"]:=__MiliSecondsToTime(jPerformReaderOut["TotalTimeIsDisqualifiedVerify"])
    jPerformReaderOut["PartialTimeIsDisqualifiedVerify"]:=__MiliSecondsToTime(jPerformReaderOut["PartialTimeIsDisqualifiedVerify"])

    ConOut(jPerformReaderOut:ToJSON())

    FreeObj(@jPerformReaderOut)

return

static function __MiliSecondsToTime(nTotalMS as numeric) as character
return(timeCalc():MiliSecsToTime(nTotalMS))

static procedure __TST_FT(cFile,jPerformReader,lStrHashLog,lSequential,lDecodeUTF8)

    local cLine as character
    local cLineSkip as character

    local nHandle as numeric

    local nRecNo as numeric
    local nRecNos as numeric

    local oFileNavigator as object

    jPerformReader["ProcStart"]:=TimeCounter()
    jPerformReader["TimeProcStart"]:=Time()

    nHandle:=fOpen(cFile)
    //FT_ nao fornece uma funcao para obter o tamanho do arquivo
    //Vamos emprestar de FileNavigator
    oFileNavigator:=FileNavigator():New(;
        nHandle;
        ,nil;
        ,{||.F.};
        ,{||""};
    )
    jPerformReader["FileSize"]:=oFileNavigator:FileSize()
    oFileNavigator:Close()

    nHandle:=ft_fUse(cFile)

    ft_fGoTop()

    if (!lSequential)
        nRecNos:=ft_fLastRec()
        while (!ft_fEof())
            *****************************************************************
            jPerformReader["Lines"]++
            *****************************************************************
            if (__IsDisqualifiedByTimeOut(jPerformReader))
                exit
            endif
            *****************************************************************
            //Teste de Navegacao
            *****************************************************************
            nRecNo:=ft_fRecNo()
            *****************************************************************
            ft_fSkip(Randomize(1,nRecNos))
            cLineSkip:=ft_fReadLN()
            *****************************************************************
            ft_fGoto(nRecNo)
            *****************************************************************
            cLine:=ft_fReadLN()
            *****************************************************************
            __StrHash(if(lDecodeUTF8,DecodeUTF8(cLine),cLine),jPerformReader,lStrHashLog)
            *****************************************************************
            __TSTStrTokArray(@cLine,@jPerformReader)
            *****************************************************************
            ft_fSkip()
        end while
    else
        while (!ft_fEof())
            *****************************************************************
            jPerformReader["Lines"]++
            *****************************************************************
            if (__IsDisqualifiedByTimeOut(jPerformReader))
                exit
            endif
            *****************************************************************
            cLine:=ft_fReadLN()
            *****************************************************************
            __StrHash(if(lDecodeUTF8,DecodeUTF8(cLine),cLine),jPerformReader,lStrHashLog)
            *****************************************************************
            __TSTStrTokArray(@cLine,@jPerformReader)
            *****************************************************************
            ft_fSkip()
        end while
    endif

    ft_fUse()

    jPerformReader["TimeProcEnd"]:=Time()
    jPerformReader["ProcEnd"]:=TimeCounter()

    __ConOut(jPerformReader,lStrHashLog)

return

static procedure __TST_FWFILEREADER(cFile,jPerformReader,lStrHashLog,lSequential,lDecodeUTF8)

    local cLine as character
    local cLineSkip as character

    //FWFILEREADER tem Bug e retorna cCRH10 ou cCRH13 indevidamente e não bate o Hash da Linha
    local cCRH10 as character
    local cCRH13 as character

    local nRecNo as numeric
    local nRecNos as numeric

    local oFileReader as object
    local oFileNavigator as object

    jPerformReader["ProcStart"]:=TimeCounter()
    jPerformReader["TimeProcStart"]:=Time()

    cCRH10:=CHR(10)
    cCRH13:=CHR(13)

    oFileReader:=FWFileReader():New(cFile)
    oFileReader:Open()

    jPerformReader["FileSize"]:=oFileReader:GetFileSize()

    if (!lSequential)

        oFileNavigator:=FileNavigator():New(;
            oFileReader:nHandLen;
            ,{|nHandle|fSeek(nHandle,0)};
            ,{||!oFileReader:HasLine()};
            ,{||oFileReader:GetLine()};
        )

        if (!lSequential)
            nRecNos:=oFileNavigator:BuildIndex()
        endif

        //Utilizo, agora, FileNavigator para Navegar pelo arquivo
        while (oFileNavigator:HasLine())
            *****************************************************************
            jPerformReader["Lines"]++
            *****************************************************************
            if (__IsDisqualifiedByTimeOut(jPerformReader))
                exit
            endif
            *****************************************************************
            //Teste de Navegacao
            //Sem suporte a Navegacao no Arquivo. Vamos usar FileNavigator
            *****************************************************************
            nRecNo:=oFileNavigator:RecNo()
            *****************************************************************
            oFileNavigator:Skip(Randomize(1,nRecNos))
            cLineSkip:=oFileNavigator:GetLine()
            *****************************************************************
            oFileNavigator:GoTo(nRecNo)
            cLine:=oFileNavigator:GetLine()
            *****************************************************************
            //FWFILEREADER tem Bug e retorna cCRH10 ou cCRH13 indevidamente e não bate o Hash da Linha
            if (cCRH10$cLine)
                cLine:=StrTran(cLine,cCRH10,"")
            endif
            if (cCRH13$cLine)
                cLine:=StrTran(cLine,cCRH13,"")
            endif
            *****************************************************************
            __StrHash(if(lDecodeUTF8,DecodeUTF8(cLine),cLine),jPerformReader,lStrHashLog)
            *****************************************************************
            __TSTStrTokArray(@cLine,@jPerformReader)
            *****************************************************************
        end while
        oFileNavigator:Close({||oFileReader:Close()})
        FreeObj(@oFileNavigator)
    else
        while (oFileReader:HasLine())
            *****************************************************************
            jPerformReader["Lines"]++
            *****************************************************************
            if (__IsDisqualifiedByTimeOut(jPerformReader))
                exit
            endif
            *****************************************************************
            cLine:=oFileReader:GetLine()
            *****************************************************************
            //FWFILEREADER tem Bug e retorna cCRH10 ou cCRH13 indevidamente e não bate o Hash da Linha
            if (cCRH10$cLine)
                cLine:=StrTran(cLine,cCRH10,"")
            endif
            if (cCRH13$cLine)
                cLine:=StrTran(cLine,cCRH13,"")
            endif
            *****************************************************************
            __StrHash(if(lDecodeUTF8,DecodeUTF8(cLine),cLine),jPerformReader,lStrHashLog)
            *****************************************************************
            __TSTStrTokArray(@cLine,@jPerformReader)
            *****************************************************************
        end while
    endif
    FreeObj(@oFileReader)

    jPerformReader["TimeProcEnd"]:=Time()
    jPerformReader["ProcEnd"]:=TimeCounter()

    __ConOut(jPerformReader,lStrHashLog)

return

static procedure __TST_TFILEREAD(cFile,jPerformReader,lStrHashLog,lSequential,lDecodeUTF8)

    local cLine as character
    local cLineSkip as character

    local nHandle as numeric

    local nRecNo as numeric
    local nRecNos as numeric

    local oFileReader as object
    local oFileNavigator as object

    jPerformReader["ProcStart"]:=TimeCounter()
    jPerformReader["TimeProcStart"]:=Time()

    oFileReader:=TFileRead():New(cFile)
    oFileReader:Open()

    jPerformReader["FileSize"]:=oFileReader:FileSize()

    if (!lSequential)

        oFileNavigator:=FileNavigator():New(;
            oFileReader:Handle();
            ,{|nHandle|fSeek(nHandle,0)};
            ,{||!oFileReader:HasLine()};
            ,{||oFileReader:GetLine()};
        )

        nRecNos:=oFileNavigator:BuildIndex()

        //Utilizo, agora, FileNavigator para Navegar pelo arquivo
        while (oFileNavigator:HasLine())
            *****************************************************************
            jPerformReader["Lines"]++
            *****************************************************************
            if (__IsDisqualifiedByTimeOut(jPerformReader))
                exit
            endif
            *****************************************************************
            //Teste de Navegacao
            //Sem suporte a Navegacao no Arquivo. Vamos usar FileNavigator
            *****************************************************************
            nRecNo:=oFileNavigator:RecNo()
            *****************************************************************
            oFileNavigator:Skip(Randomize(1,nRecNos))
            cLineSkip:=oFileNavigator:GetLine()
            *****************************************************************
            oFileNavigator:GoTo(nRecNo)
            cLine:=oFileNavigator:GetLine()
            *****************************************************************
            __StrHash(if(lDecodeUTF8,DecodeUTF8(cLine),cLine),jPerformReader,lStrHashLog)
            *****************************************************************
            __TSTStrTokArray(@cLine,@jPerformReader)
            *****************************************************************
        end while

        oFileNavigator:Close({||oFileReader:Close()})
        FreeObj(@oFileNavigator)

    else

        while (oFileReader:HasLine())
            *****************************************************************
            jPerformReader["Lines"]++
            *****************************************************************
            if (__IsDisqualifiedByTimeOut(jPerformReader))
                exit
            endif
            *****************************************************************
            cLine:=oFileReader:GetLine()
            *****************************************************************
            __StrHash(if(lDecodeUTF8,DecodeUTF8(cLine),cLine),jPerformReader,lStrHashLog)
            *****************************************************************
            __TSTStrTokArray(@cLine,@jPerformReader)
            *****************************************************************
        end while

    endif
    FreeObj(@oFileReader)

    jPerformReader["TimeProcEnd"]:=Time()
    jPerformReader["ProcEnd"]:=TimeCounter()

    __ConOut(jPerformReader,lStrHashLog)

return

static procedure __TST_FILEREADER(cFile,jPerformReader,lStrHashLog,lSequential,lDecodeUTF8)

    local cLine as character
    local cLineSkip as character

    local oFileReader as object

    local nRecNo as numeric
    local nRecNos as numeric

    jPerformReader["ProcStart"]:=TimeCounter()
    jPerformReader["TimeProcStart"]:=Time()

    oFileReader:=fileTools():FileReader(jPerformReader["RDD"])
    oFileReader:ft_fUse(cFile)

    jPerformReader["FileSize"]:=oFileReader:ft_fFileSize()

    if (!lSequential)
        nRecNos:=oFileReader:ft_fLastRec()
        while (!oFileReader:ft_fEof())
            *****************************************************************
            jPerformReader["Lines"]++
            *****************************************************************
            if (__IsDisqualifiedByTimeOut(jPerformReader))
                exit
            endif
            *****************************************************************
            //Teste de Navegacao
            *****************************************************************
            nRecNo:=oFileReader:ft_fRecNo()
            *****************************************************************
            oFileReader:ft_fSkip(Randomize(1,nRecNos))
            cLineSkip:=oFileReader:ft_fReadLN()
            *****************************************************************
            oFileReader:ft_fGoto(nRecNo)
            *****************************************************************
            cLine:=oFileReader:ft_fReadLN()
            *****************************************************************
            __StrHash(if(lDecodeUTF8,DecodeUTF8(cLine),cLine),jPerformReader,lStrHashLog)
            *****************************************************************
            __TSTStrTokArray(@cLine,@jPerformReader)
            *****************************************************************
            oFileReader:ft_fSkip()
        end while
    else
        while (!oFileReader:ft_fEof())
            *****************************************************************
            jPerformReader["Lines"]++
            *****************************************************************
            if (__IsDisqualifiedByTimeOut(jPerformReader))
                exit
            endif
            *****************************************************************
            cLine:=oFileReader:ft_fReadLN()
            *****************************************************************
            __StrHash(if(lDecodeUTF8,DecodeUTF8(cLine),cLine),jPerformReader,lStrHashLog)
            *****************************************************************
            __TSTStrTokArray(@cLine,@jPerformReader)
            *****************************************************************
            oFileReader:ft_fSkip()
        end while
    endif

    oFileReader:ft_fUse()
    FreeObj(@oFileReader)

    jPerformReader["TimeProcEnd"]:=Time()
    jPerformReader["ProcEnd"]:=TimeCounter()

    __ConOut(jPerformReader,lStrHashLog)

return

static function __IsDisqualifiedByTimeOut(jPerformReader as json) as logical
    local nTimeCounter:=TimeCounter() as numeric
    local lIsDisqualifiedByTimeOut as logical
    jPerformReader["PartialTimeProc"]:=(nTimeCounter-jPerformReader["ProcStart"])
    lIsDisqualifiedByTimeOut:=(jPerformReader["PartialTimeProc"]>jPerformReader["TimeOutThresHold"])
    jPerformReader["IsDisqualifiedByTimeOut"]:=lIsDisqualifiedByTimeOut
    jPerformReader["PartialTimeIsDisqualifiedVerify"]+=(TimeCounter()-nTimeCounter)
return(lIsDisqualifiedByTimeOut)
