using namespace dna.tech

procedure u_fileIOPF()
    __cInternet:=nil
    u_fileIOPerform()
return

procedure u_fileIOPerform()
    __cInternet:=nil
    FWMsgRun(nil,{|oSay|fileIOPerform(oSay)},"fileIOPerform","Aguarde...")
return

static procedure fileIOPerform(oSay as object)

    local aLine as array
    local aFiles:={;
        "\datasul2protheus\tables\funcionario.csv";
       ,"\datasul2protheus\tablessplit\marcac_ptoelet\marcac_ptoelet_001_20250618_155833_573656_984.csv";
    } as array
    local aPerform:={;
        "TFileRead";
       ,"FWFileReader";
       ,"FileReader_FILE";
       ,"FileReader_HASHMAP";
       ,"FileReader_SQLITE_MEM";
       ,"FileReader_SQLITE_TMP";
       ,"FileReader_TOPCONN";
       ,"ft_fUse";
    } as array

    local cLine as character
    local cFile as character

    local nFile as numeric

    local nStrTokTime as numeric
    local nTimeCounter as numeric

    local nElapTimeTotal as numeric
    local nElapTimeReader as numeric

    local nStrTokElapTime1:=0 as numeric
    local nStrTokElapTime2:=0 as numeric
    local nStrTokElapTime3:=0 as numeric

    local oFileReader as object

    local i as numeric

    local nCols1:=0 as numeric
    local nCols2:=0 as numeric
    local nCols3:=0 as numeric
    local nLines:=0 as numeric

    for nFile:=1 to Len(aFiles)
        cFile:=aFiles[nFile]
        for i:=1 to Len(aPerform)
            oSay:SetText(aPerform[i])
            nCols1:=0
            nCols2:=0
            nCols3:=0
            nLines:=0
            nStrTokElapTime1:=0
            nStrTokElapTime2:=0
            nStrTokElapTime3:=0
            if (aPerform[i]=="ft_fUse")
                nTimeCounter:=TimeCounter()
                ft_fUse(cFile)
                ft_fGoTop()
                while (!ft_fEof())
                    nLines++
                    cLine:=ft_fReadLn()
                    *****************************************************************
                    nStrTokTime:=TimeCounter()
                        aLine:=StrTokArr2(cLine,";")
                    nStrTokElapTime1+=(TimeCounter()-nStrTokTime)
                    nCols1+=Len(aLine)
                    *****************************************************************
                    FWFreeArray(@aLine)
                    *****************************************************************
                    nStrTokTime:=TimeCounter()
                        aLine:=cTools():__StrTokArray(cLine,";",1,nil,{})
                    nStrTokElapTime2+=(TimeCounter()-nStrTokTime)
                    nCols2+=Len(aLine)
                    *****************************************************************
                    FWFreeArray(@aLine)
                    *****************************************************************
                    nStrTokTime:=TimeCounter()
                        aLine:=StrTokArr(cLine,";")
                    nStrTokElapTime3+=(TimeCounter()-nStrTokTime)
                    nCols3+=Len(aLine)
                    *****************************************************************
                    FWFreeArray(@aLine)
                    *****************************************************************
                    ft_fSkip()
                end while
                ft_fUse()
                nElapTimeTotal:=(TimeCounter()-nTimeCounter)
                nElapTimeReader:=(nElapTimeTotal-(nStrTokElapTime1+nStrTokElapTime2+nStrTokElapTime3))
                ConOut(aPerform[i]+" => ElapTimeReader["+LTrim(Str(nElapTimeReader))+"] => Lines["+LTrim(Str(nLines))+"] => ElapTimeTotal["+LTrim(Str(nElapTimeTotal))+"] => Cols1[("+LTrim(Str(nCols1))+")|("+LTrim(Str(nStrTokElapTime1))+")] => Cols2[("+LTrim(Str(nCols2))+")|("+LTrim(Str(nStrTokElapTime2))+")] => Cols3[("+LTrim(Str(nCols3))+")|("+LTrim(Str(nStrTokElapTime3))+")]")
            elseif aPerform[i]=="FWFileReader"
                nTimeCounter:=TimeCounter()
                oFileReader:=FWFileReader():New(cFile)
                oFileReader:Open()
                while (oFileReader:HasLine())
                    nLines++
                    cLine:=oFileReader:GetLine()
                    *****************************************************************
                    nStrTokTime:=TimeCounter()
                        aLine:=StrTokArr2(cLine,";")
                    nStrTokElapTime1+=(TimeCounter()-nStrTokTime)
                    nCols1+=Len(aLine)
                    *****************************************************************
                    FWFreeArray(@aLine)
                    *****************************************************************
                    nStrTokTime:=TimeCounter()
                        aLine:=cTools():__StrTokArray(cLine,";",1,nil,{})
                    nStrTokElapTime2+=(TimeCounter()-nStrTokTime)
                    nCols2+=Len(aLine)
                    *****************************************************************
                    FWFreeArray(@aLine)
                    *****************************************************************
                    nStrTokTime:=TimeCounter()
                        aLine:=StrTokArr(cLine,";")
                    nStrTokElapTime3+=(TimeCounter()-nStrTokTime)
                    nCols3+=Len(aLine)
                    *****************************************************************
                    FWFreeArray(@aLine)
                    *****************************************************************
                end while
                oFileReader:Close()
                FreeObj(@oFileReader)
                nElapTimeTotal:=(TimeCounter()-nTimeCounter)
                nElapTimeReader:=(nElapTimeTotal-(nStrTokElapTime1+nStrTokElapTime2+nStrTokElapTime3))
                ConOut(aPerform[i]+" => ElapTimeReader["+LTrim(Str(nElapTimeReader))+"] => Lines["+LTrim(Str(nLines))+"] => ElapTimeTotal["+LTrim(Str(nElapTimeTotal))+"] => Cols1[("+LTrim(Str(nCols1))+")|("+LTrim(Str(nStrTokElapTime1))+")] => Cols2[("+LTrim(Str(nCols2))+")|("+LTrim(Str(nStrTokElapTime2))+")] => Cols3[("+LTrim(Str(nCols3))+")|("+LTrim(Str(nStrTokElapTime3))+")]")
            elseif aPerform[i]=="TFileRead"
                nTimeCounter:=TimeCounter()
                oFileReader:=TFileRead():New(cFile)
                oFileReader:Open()
                while (oFileReader:MoreToRead())
                    nLines++
                    cLine:=oFileReader:ReadLine()
                    *****************************************************************
                    nStrTokTime:=TimeCounter()
                        aLine:=StrTokArr2(cLine,";")
                    nStrTokElapTime1+=(TimeCounter()-nStrTokTime)
                    nCols1+=Len(aLine)
                    *****************************************************************
                    FWFreeArray(@aLine)
                    *****************************************************************
                    nStrTokTime:=TimeCounter()
                        aLine:=cTools():__StrTokArray(cLine,";",1,nil,{})
                    nStrTokElapTime2+=(TimeCounter()-nStrTokTime)
                    nCols2+=Len(aLine)
                    *****************************************************************
                    FWFreeArray(@aLine)
                    *****************************************************************
                    nStrTokTime:=TimeCounter()
                        aLine:=StrTokArr(cLine,";")
                    nStrTokElapTime3+=(TimeCounter()-nStrTokTime)
                    nCols3+=Len(aLine)
                    *****************************************************************
                    FWFreeArray(@aLine)
                    *****************************************************************
                end while
                oFileReader:Close()
                FreeObj(@oFileReader)
                nElapTimeTotal:=(TimeCounter()-nTimeCounter)
                nElapTimeReader:=(nElapTimeTotal-(nStrTokElapTime1+nStrTokElapTime2+nStrTokElapTime3))
                ConOut(aPerform[i]+" => ElapTimeReader["+LTrim(Str(nElapTimeReader))+"] => Lines["+LTrim(Str(nLines))+"] => ElapTimeTotal["+LTrim(Str(nElapTimeTotal))+"] => Cols1[("+LTrim(Str(nCols1))+")|("+LTrim(Str(nStrTokElapTime1))+")] => Cols2[("+LTrim(Str(nCols2))+")|("+LTrim(Str(nStrTokElapTime2))+")] => Cols3[("+LTrim(Str(nCols3))+")|("+LTrim(Str(nStrTokElapTime3))+")]")
            elseif aPerform[i]=="FileReader_HASHMAP"
                nTimeCounter:=TimeCounter()
                oFileReader:=fileTools():FileReader("HASHMAP")
                oFileReader:ft_fUse(cFile)
                while (!oFileReader:ft_fEof())
                    nLines++
                    cLine:=oFileReader:ft_fReadLN()
                    *****************************************************************
                    nStrTokTime:=TimeCounter()
                        aLine:=StrTokArr2(cLine,";")
                    nStrTokElapTime1+=(TimeCounter()-nStrTokTime)
                    nCols1+=Len(aLine)
                    *****************************************************************
                    FWFreeArray(@aLine)
                    *****************************************************************
                    nStrTokTime:=TimeCounter()
                        aLine:=cTools():__StrTokArray(cLine,";",1,nil,{})
                    nStrTokElapTime2+=(TimeCounter()-nStrTokTime)
                    nCols2+=Len(aLine)
                    *****************************************************************
                    FWFreeArray(@aLine)
                    *****************************************************************
                    nStrTokTime:=TimeCounter()
                        aLine:=StrTokArr(cLine,";")
                    nStrTokElapTime3+=(TimeCounter()-nStrTokTime)
                    nCols3+=Len(aLine)
                    *****************************************************************
                    FWFreeArray(@aLine)
                    *****************************************************************
                    oFileReader:ft_fSkip()
                end while
                oFileReader:ft_fUse()
                FreeObj(@oFileReader)
                nElapTimeTotal:=(TimeCounter()-nTimeCounter)
                nElapTimeReader:=(nElapTimeTotal-(nStrTokElapTime1+nStrTokElapTime2+nStrTokElapTime3))
                ConOut(aPerform[i]+" => ElapTimeReader["+LTrim(Str(nElapTimeReader))+"] => Lines["+LTrim(Str(nLines))+"] => ElapTimeTotal["+LTrim(Str(nElapTimeTotal))+"] => Cols1[("+LTrim(Str(nCols1))+")|("+LTrim(Str(nStrTokElapTime1))+")] => Cols2[("+LTrim(Str(nCols2))+")|("+LTrim(Str(nStrTokElapTime2))+")] => Cols3[("+LTrim(Str(nCols3))+")|("+LTrim(Str(nStrTokElapTime3))+")]")
            elseif aPerform[i]=="FileReader_FILE"
                nTimeCounter:=TimeCounter()
                oFileReader:=fileTools():FileReader("FILE")
                oFileReader:ft_fUse(cFile)
                while (!oFileReader:ft_fEof())
                    nLines++
                    cLine:=oFileReader:ft_fReadLN()
                    *****************************************************************
                    nStrTokTime:=TimeCounter()
                        aLine:=StrTokArr2(cLine,";")
                    nStrTokElapTime1+=(TimeCounter()-nStrTokTime)
                    nCols1+=Len(aLine)
                    *****************************************************************
                    FWFreeArray(@aLine)
                    *****************************************************************
                    nStrTokTime:=TimeCounter()
                        aLine:=cTools():__StrTokArray(cLine,";",1,nil,{})
                    nStrTokElapTime2+=(TimeCounter()-nStrTokTime)
                    nCols2+=Len(aLine)
                    *****************************************************************
                    FWFreeArray(@aLine)
                    *****************************************************************
                    nStrTokTime:=TimeCounter()
                        aLine:=StrTokArr(cLine,";")
                    nStrTokElapTime3+=(TimeCounter()-nStrTokTime)
                    nCols3+=Len(aLine)
                    *****************************************************************
                    FWFreeArray(@aLine)
                    *****************************************************************
                    oFileReader:ft_fSkip()
                end while
                oFileReader:ft_fUse()
                FreeObj(@oFileReader)
                nElapTimeTotal:=(TimeCounter()-nTimeCounter)
                nElapTimeReader:=(nElapTimeTotal-(nStrTokElapTime1+nStrTokElapTime2+nStrTokElapTime3))
                ConOut(aPerform[i]+" => ElapTimeReader["+LTrim(Str(nElapTimeReader))+"] => Lines["+LTrim(Str(nLines))+"] => ElapTimeTotal["+LTrim(Str(nElapTimeTotal))+"] => Cols1[("+LTrim(Str(nCols1))+")|("+LTrim(Str(nStrTokElapTime1))+")] => Cols2[("+LTrim(Str(nCols2))+")|("+LTrim(Str(nStrTokElapTime2))+")] => Cols3[("+LTrim(Str(nCols3))+")|("+LTrim(Str(nStrTokElapTime3))+")]")
            elseif aPerform[i]=="FileReader_SQLITE_MEM"
                nTimeCounter:=TimeCounter()
                oFileReader:=fileTools():FileReader("SQLITE_MEM")
                oFileReader:ft_fUse(cFile)
                while (!oFileReader:ft_fEof())
                    nLines++
                    cLine:=oFileReader:ft_fReadLN()
                    *****************************************************************
                    nStrTokTime:=TimeCounter()
                        aLine:=StrTokArr2(cLine,";")
                    nStrTokElapTime1+=(TimeCounter()-nStrTokTime)
                    nCols1+=Len(aLine)
                    *****************************************************************
                    FWFreeArray(@aLine)
                    *****************************************************************
                    nStrTokTime:=TimeCounter()
                        aLine:=cTools():__StrTokArray(cLine,";",1,nil,{})
                    nStrTokElapTime2+=(TimeCounter()-nStrTokTime)
                    nCols2+=Len(aLine)
                    *****************************************************************
                    FWFreeArray(@aLine)
                    *****************************************************************
                    nStrTokTime:=TimeCounter()
                        aLine:=StrTokArr(cLine,";")
                    nStrTokElapTime3+=(TimeCounter()-nStrTokTime)
                    nCols3+=Len(aLine)
                    *****************************************************************
                    FWFreeArray(@aLine)
                    *****************************************************************
                    oFileReader:ft_fSkip()
                end while
                oFileReader:ft_fUse()
                FreeObj(@oFileReader)
                nElapTimeTotal:=(TimeCounter()-nTimeCounter)
                nElapTimeReader:=(nElapTimeTotal-(nStrTokElapTime1+nStrTokElapTime2+nStrTokElapTime3))
                ConOut(aPerform[i]+" => ElapTimeReader["+LTrim(Str(nElapTimeReader))+"] => Lines["+LTrim(Str(nLines))+"] => ElapTimeTotal["+LTrim(Str(nElapTimeTotal))+"] => Cols1[("+LTrim(Str(nCols1))+")|("+LTrim(Str(nStrTokElapTime1))+")] => Cols2[("+LTrim(Str(nCols2))+")|("+LTrim(Str(nStrTokElapTime2))+")] => Cols3[("+LTrim(Str(nCols3))+")|("+LTrim(Str(nStrTokElapTime3))+")]")
            elseif aPerform[i]=="FileReader_SQLITE_TMP"
                nTimeCounter:=TimeCounter()
                oFileReader:=fileTools():FileReader("SQLITE_TMP")
                oFileReader:ft_fUse(cFile)
                while (!oFileReader:ft_fEof())
                    nLines++
                    cLine:=oFileReader:ft_fReadLN()
                    *****************************************************************
                    nStrTokTime:=TimeCounter()
                        aLine:=StrTokArr2(cLine,";")
                    nStrTokElapTime1+=(TimeCounter()-nStrTokTime)
                    nCols1+=Len(aLine)
                    *****************************************************************
                    FWFreeArray(@aLine)
                    *****************************************************************
                    nStrTokTime:=TimeCounter()
                        aLine:=cTools():__StrTokArray(cLine,";",1,nil,{})
                    nStrTokElapTime2+=(TimeCounter()-nStrTokTime)
                    nCols2+=Len(aLine)
                    *****************************************************************
                    FWFreeArray(@aLine)
                    *****************************************************************
                    nStrTokTime:=TimeCounter()
                        aLine:=StrTokArr(cLine,";")
                    nStrTokElapTime3+=(TimeCounter()-nStrTokTime)
                    nCols3+=Len(aLine)
                    *****************************************************************
                    FWFreeArray(@aLine)
                    *****************************************************************
                    oFileReader:ft_fSkip()
                end while
                oFileReader:ft_fUse()
                FreeObj(@oFileReader)
                nElapTimeTotal:=(TimeCounter()-nTimeCounter)
                nElapTimeReader:=(nElapTimeTotal-(nStrTokElapTime1+nStrTokElapTime2+nStrTokElapTime3))
                ConOut(aPerform[i]+" => ElapTimeReader["+LTrim(Str(nElapTimeReader))+"] => Lines["+LTrim(Str(nLines))+"] => ElapTimeTotal["+LTrim(Str(nElapTimeTotal))+"] => Cols1[("+LTrim(Str(nCols1))+")|("+LTrim(Str(nStrTokElapTime1))+")] => Cols2[("+LTrim(Str(nCols2))+")|("+LTrim(Str(nStrTokElapTime2))+")] => Cols3[("+LTrim(Str(nCols3))+")|("+LTrim(Str(nStrTokElapTime3))+")]")
            elseif aPerform[i]=="FileReader_TOPCONN"
                nTimeCounter:=TimeCounter()
                oFileReader:=fileTools():FileReader("TOPCONN")
                oFileReader:ft_fUse(cFile)
                while (!oFileReader:ft_fEof())
                    nLines++
                    cLine:=oFileReader:ft_fReadLN()
                    *****************************************************************
                    nStrTokTime:=TimeCounter()
                        aLine:=StrTokArr2(cLine,";")
                    nStrTokElapTime1+=(TimeCounter()-nStrTokTime)
                    nCols1+=Len(aLine)
                    *****************************************************************
                    FWFreeArray(@aLine)
                    *****************************************************************
                    nStrTokTime:=TimeCounter()
                        aLine:=cTools():__StrTokArray(cLine,";",1,nil,{})
                    nStrTokElapTime2+=(TimeCounter()-nStrTokTime)
                    nCols2+=Len(aLine)
                    *****************************************************************
                    FWFreeArray(@aLine)
                    *****************************************************************
                    nStrTokTime:=TimeCounter()
                        aLine:=StrTokArr(cLine,";")
                    nStrTokElapTime3+=(TimeCounter()-nStrTokTime)
                    nCols3+=Len(aLine)
                    *****************************************************************
                    FWFreeArray(@aLine)
                    *****************************************************************
                    oFileReader:ft_fSkip()
                end while
                oFileReader:ft_fUse()
                FreeObj(@oFileReader)
                nElapTimeTotal:=(TimeCounter()-nTimeCounter)
                nElapTimeReader:=(nElapTimeTotal-(nStrTokElapTime1+nStrTokElapTime2+nStrTokElapTime3))
                ConOut(aPerform[i]+" => ElapTimeReader["+LTrim(Str(nElapTimeReader))+"] => Lines["+LTrim(Str(nLines))+"] => ElapTimeTotal["+LTrim(Str(nElapTimeTotal))+"] => Cols1[("+LTrim(Str(nCols1))+")|("+LTrim(Str(nStrTokElapTime1))+")] => Cols2[("+LTrim(Str(nCols2))+")|("+LTrim(Str(nStrTokElapTime2))+")] => Cols3[("+LTrim(Str(nCols3))+")|("+LTrim(Str(nStrTokElapTime3))+")]")
            endif
        next i
    next nFile

    FWFreeArray(@aLine)
    FWFreeArray(@aFiles)
    FWFreeArray(@aPerform)

return
