#DEFINE DTS_DBS_NAME   1
#DEFINE DTS_DBS_TYPE   2
#DEFINE DTS_DBS_FLG    3
#DEFINE DTS_DBS_FORMAT 4

#DEFINE DTS_DBS_ALEN   4

#include "totvs.ch"
#include "shell.ch"

#include "dbstruct.ch"

#include "jsonhash.ch"
#include "jsonarray.ch"

namespace datasul2totvs

#include "execin.th"
EXECIN CLASS datasul2totvs

static function GetValue(xGet as variant,xDefault as variant) as variant
return(cacheData():Get("datasul2totvsprotheus",xGet,xDefault))

static function SetValue(xVar as variant,xValue as variant) as variant
return(cacheData():Set("datasul2totvsprotheus",xVar,xValue))

static function DelProperty(xProperty as variant) as variant
return(cacheData():delProperty("datasul2totvsprotheus",xProperty))

static function DelSection(xSection as variant) as variant
    dfv():Default(@xSection,"datasul2totvsprotheus")
return(cacheData():delSection(xSection))

static function EvalBlockGetValue(xGet as variant,xDefault as variant) as variant
return(cacheData():Get("EvalBlock",xGet,xDefault))

class Protheus
    static method Activate() as logical
end class

static method Activate() class Protheus

    local lActivate as logical
    local lSetCentury:=__SetCentury("ON") as logical
    local nSetVarNameLen:=SetVarNameLen(Max(SetVarNameLen(),254))

    private cCadastro:="TOTVS :: DataSul To Protheus" as character

    lActivate:=((FWIsAdmin(__cUserID)).and.(GetNewPar("TOTVSDS2PT",.T.)))
    if (!lActivate)
        ApMsgAlert("User without administrative privileges")
    else
        lActivate:=datasul2totvs.Activate()
    endif

    __SetCentury(if(lSetCentury,"ON","OFF"))
    SetVarNameLen(nSetVarNameLen)

return(lActivate)

static function Activate() as logical

    local aStack:={"DATASUL2TOTVS.ACTIVATE","ACTIVATE","U_DATASUL2TOTVSPROTHEUS"} as array
    local aSections as array
    local aProperties as array

    local bTMenuAction as codeblock

    local cAlias as character
    local cSection as character
    local cProperty as character
    local cTMenuAction as character
    local cGetFileRoot:="\" as character
    local cGetFileMask as character
    local cGetFileTitle as character

    local lFastMode as logical
    local lPercentage as logical

    local lActivate as logical
    local lSendDataToServer as logical

    local nSection as numeric
    local nSections as numeric
    local nProperty as numeric
    local nProperties as numeric
    local nGetFileOptions as numeric

    local oTDlg as object
    local oTMenu as object
    local oFWDefSize as object

    local oTFIni as object

    local oTMenuItem as object
    local oTMenuOptions as object

    begin sequence

        lActivate:=stacktools():IsInStackCall(aStack)
        if (!lActivate)
            break
        endif

        private st_oHMbTransform:=THashMap():New() as object

        lSendDataToServer:=(;
            (getComputerName()$(GetNewPar("TOTVSD2PCN","DNA-CSDJ-01")));
            .and.;
            (ApMsgNoYes("Sending Data To Server?"));
        )

        if (lSendDataToServer)
            MsProcess():MsAguarde({||lSendDataToServer:=datasul2totvs.sendDataToServer(@cGetFileRoot,.F.)},"Sending Data To Server","Wait!")
        elseif (file("\datasul2Protheus\ini\DataSul2Protheus.ini"))
            cGetFileRoot:="SERVIDOR\datasul2protheus\ini\"
        endif

        cGetFileMask:=cTools():Accentuation("Arquivo de Configura#1#2o | DataSul2Protheus.ini","ccedil","atilde")
        cGetFileTitle:=cTools():Accentuation("Arquivo de Configura#1#2o DataSul2Protheus.ini","ccedil","atilde")
        
        nGetFileOptions:=(GETF_LOCALHARD+GETF_NETWORKDRIVE)

        cINIFile:=cGetFile(;
            cGetFileMask,;
            cGetFileTitle,;
            1,;
            cGetFileRoot,;
            .F.,;
            nGetFileOptions,;
            /*[lArvore]*/,;
            /*[lKeepCase]*/;
        )

        lActivate:=file(cINIFile)
        if (!lActivate)
            ApMsgAlert("Configuration file invalid ["+cINIFile+"] or not found","Attention")
            break
        endif

        lActivate:=("datasul2protheus.ini"$lower(cINIFile))
        if (!lActivate)
            ApMsgAlert("Configuration file invalid ["+cINIFile+"] or not found","Attention")
            break
        endif

        MsProcess():MsAguarde({||lActivate:=datasul2totvs.readIniFile(@cINIFile)},"Loading Settings","Wait! Loading ["+cINIFile+"]")
        if (!lActivate)
            break
        endif

        MsProcess():MsAguarde({||lActivate:=datasul2totvs.readTableDefinition()},"Loading structure of tables","Wait")
        if (!lActivate)
            break
        endif

        oTFIni:=GetValue("readIniFile")

        lActivate:=(allTrim(oTFIni:GetPropertyValue("General","CompanyCode","@@"))==&("cEmpAnt"))
        if (!lActivate)
            ApMsgAlert("The import process cannot be performed for the Selected Company ["+&("cEmpAnt")+"]","Attention")
            break
        endif

        lFastMode:=(allTrim(oTFIni:GetPropertyValue("General","IncProcFastMode","0"))=="1")
        lPercentage:=(allTrim(oTFIni:GetPropertyValue("General","IncProcPercentage","0"))=="1")

        oFWDefSize:=FWDefSize():New(.T.,.T.)//Sem enchoicebar
        oFWDefSize:lLateral:=.F.//Calculo vertical
        oFWDefSize:AddObject("TMENU",100,100,.T.,.T.)//TMENU

        oFWDefSize:Process()

        nTop:=oFWDefSize:aWindSize[1]
        nLeft:=oFWDefSize:aWindSize[2]
        nBottom:=oFWDefSize:aWindSize[3]
        nRight:=oFWDefSize:aWindSize[4]

        oTMenuOptions:=Array(#)

        cSection:="Register"
        oTMenuOptions[#cSection]:=Array(#)
        oTMenuOptions[#cSection][#"Alias"]:=Array(#)
        oTMenuOptions[#cSection][#"Alias"][#"01"]:="SRJ"
        oTMenuOptions[#cSection][#"Alias"][#"02"]:="SR6"
*       oTMenuOptions[#cSection][#"Alias"][#"03"]:="SPJ"
        oTMenuOptions[#cSection][#"Alias"][#"04"]:="RCE"
        oTMenuOptions[#cSection][#"Alias"][#"05"]:="SQB"
        oTMenuOptions[#cSection][#"Alias"][#"06"]:="SRV"

        cSection:="Employee"
        oTMenuOptions[#cSection]:=Array(#)
        oTMenuOptions[#cSection][#"Alias"]:=Array(#)
        oTMenuOptions[#cSection][#"Alias"][#"01"]:="SRA"
        oTMenuOptions[#cSection][#"Alias"][#"02"]:="SRB"
        oTMenuOptions[#cSection][#"Alias"][#"03"]:="SRQ"

        cSection:="Employee Transaction History"
        oTMenuOptions[#cSection]:=Array(#)
        oTMenuOptions[#cSection][#"Alias"]:=Array(#)
        oTMenuOptions[#cSection][#"Alias"][#"01"]:="SR3"
        oTMenuOptions[#cSection][#"Alias"][#"02"]:="SRF"
        oTMenuOptions[#cSection][#"Alias"][#"03"]:="SR8"
        oTMenuOptions[#cSection][#"Alias"][#"04"]:="SRD"

        cSection:="Employee Benefits"
        oTMenuOptions[#cSection]:=Array(#)
        oTMenuOptions[#cSection][#"Alias"]:=Array(#)
        oTMenuOptions[#cSection][#"Alias"][#"01"]:="RI1"
        oTMenuOptions[#cSection][#"Alias"][#"02"]:="SM7"
        oTMenuOptions[#cSection][#"Alias"][#"03"]:="RHK"
        oTMenuOptions[#cSection][#"Alias"][#"04"]:="RHL"

        cSection:="Employee Punch Marking"
        oTMenuOptions[#cSection]:=Array(#)
        oTMenuOptions[#cSection][#"Alias"]:=Array(#)
        oTMenuOptions[#cSection][#"Alias"][#"01"]:="SP8"

        DEFINE MSDIALOG oTDlg TITLE cCadastro FROM nTop,nLeft TO nBottom,nRight PIXEL OF getWNDDefault()

            MENU oTMenu IMAGE "" OF oTDlg
                MENUITEM cCadastro
                MENU
                    aSections:=aClone(oTMenuOptions:GetAllSections())
                    nSections:=Len(aSections)
                    for nSection:=1 to nSections
                        cSection:=aSections[nSection]
                        aProperties:=aClone(oTMenuOptions[#cSection][#"Alias"]:GetAllSections())
                        nProperties:=Len(aProperties)
                        MENUITEM cSection
                        MENU
                            for nProperty:=1 to nProperties
                                cProperty:=aProperties[nProperty]
                                cAlias:=oTMenuOptions[#cSection][#"Alias"][#cProperty]
                                beginContent var cTMenuAction
                                    {||datasul2totvs.ProcImportData("cAlias",lPercentage,lFastMode)}
                                endContent
                                cTMenuAction:=cTools():StrReplace(;
                                    cTMenuAction,;
                                    {CRLF,""},;
                                    {CHR(10),""},;
                                    {CHR(13),""},;
                                    {" ",""},;
                                    {"cAlias",cAlias},;
                                    {"lPercentage",IF(lPercentage,".T.",".F.")},;
                                    {"lFastMode",IF(lFastMode,".T.",".F.")};
                                )
                                bTMenuAction:=&(cTMenuAction)
                                cTMenuAction:=""
                                MENUITEM oTMenuItem PROMPT cAlias+" :: "+Upper(FWSX2Util():GetX2Name(cAlias,.F.))
                                oTMenuItem:bAction:=bTMenuAction
                            next nProperty
                        ENDMENU
                        FWFreeArray(@aProperties)
                    next nSection
                    FWFreeArray(@aSections)
                ENDMENU
                MENUITEM "Tools"
                MENU
                    bTMenuAction:={||lSendDataToServer:=datasul2totvs.sendDataToServer(@cGetFileRoot,.T.)}
                    MENUITEM "Send data to the server" ACTION MsProcess():MsAguarde(bTMenuAction,"Sending Data To Server","Wait!")
                    MENUITEM "Settings" ACTION CFGFile()
                ENDMENU
                MENU
                    MENUITEM "Exit" ACTION oTDlg:End()
                ENDMENU
            ENDMENU

            oTMenu:align:=CONTROL_ALIGN_LEFT
            oTDlg:SetMenu(oTMenu)

        ACTIVATE DIALOG oTDlg CENTERED

        MsProcess():MsAguarde({||oTMenuOptions:FreeObj()},"Releasing temporary files and workspace memory...","Wait...")
        if (valType(oTMenuOptions)=="O")
            oTMenuOptions:=FreeObj(oTMenuOptions)
        endif

        oTMenuItem:=FreeObj(oTMenuItem)
        oTMenu:=FreeObj(oTMenu)
        oTDlg:=FreeObj(oTDlg)

    end sequence

    if (valType(oTFIni)=="O")
        MsProcess():MsAguarde({||oTFIni:FreeObj()},"Releasing temporary files and workspace memory...","Wait...")
        if (valType(oTFIni)=="O")
            oTFIni:=FreeObj(oTFIni)
        endif
    endif

    FWFreeArray(@aStack)
    FWFreeArray(@aSections)
    FWFreeArray(@aProperties)

    MsProcess():MsAguarde({||DelSection()},"Releasing temporary files and workspace memory...","Wait...")

    if (findFunction("RstPosAlias"))
        RstPosAlias()
    endif

    if (valType(st_oHMbTransform)=="O")
        MsProcess():MsAguarde({||st_oHMbTransform:Clean()},"Releasing temporary files and workspace memory...","Wait...")
        st_oHMbTransform:=FreeObj(st_oHMbTransform)
    endif

    DelClassIntF()

return(lActivate)

static function ProcImportData(cAlias as character,lPercentage as logical,lFastMode as logical) as logical

    local aByRef as array

    local bProcImportData as codeblock

    local cMsgProcImportData as character

    local lEnd as logical
    local lEvalOK as logical
    local lImportData as logical

    local oTFont as object
    local oParameters:=Array(#) as object
    local oMSNewProcess as object

    cMsgProcImportData:="Importing :: "
    cMsgProcImportData+=cAlias
    cMsgProcImportData+=" :: "
    cMsgProcImportData+=Upper(FWSX2Util():GetX2Name(cAlias,.F.))
    cMsgProcImportData+=" :: ["+DToC(Date())+"]["+Time()+"]"

    oTFont:=TFont():New("Courier New",nil,16,nil,.T.)
    bProcImportData:={||;
        datasul2totvs.ProcRedefine(;
            oMSNewProcess,;
            @oTFont,;
            0,;
            650,;
            650,;
            .T.,;
            .T.,;
            lPercentage,;
            lFastMode;
        ),;
        lImportData:=ExecIn():evalJSONArrayObject(@oParameters,@aByRef,@lEvalOK);
    }
    oMSNewProcess:=MsNewProcess():New(bProcImportData,cMsgProcImportData,"Wait!",.T.)

    oParameters[#"ClassName"]:=cAlias+"Import"
    oParameters[#"FunctionName"]:=cAlias+"ImportData"
    oParameters[#"FunctionParameters"]:=Array(#)
    oParameters[#"FunctionParameters"][#"oMSNewProcess"]:=oMSNewProcess
    oParameters[#"FunctionParameters"][#"lEnd"]:=lEnd
    oParameters[#"FunctionParameters"][#"lPercentage"]:=lPercentage

    oMSNewProcess:Activate()

    if (lEvalOK)
        lEnd:=aByRef[2]
    else
        lImportData:=.F.
    endif

    oParameters[#"ClassName"]:=nil
    oParameters[#"FunctionName"]:=nil
    oParameters[#"FunctionParameters"][#"oMSNewProcess"]:=nil
    oParameters[#"FunctionParameters"][#"lEnd"]:=nil
    oParameters[#"FunctionParameters"]:FreeObj()

    oParameters:FreeObj()
    if (valType(oParameters)=="O")
        oParameters:=FreeObj(oParameters)
    endif

    oTFont:=FreeObj(oTFont)
    oMSNewProcess:=FreeObj(oMSNewProcess)

    FWFreeArray(@aByRef)

    DelClassIntF()

return(lImportData)

static function ImportData(oMsNewProcess as object,lEnd as logical,lPercentage as logical,oTLogReport as object,cAlias as character,cIndexKey as character,cTableImport as character,aAddIndex as array,lPreLoadTable as logical,bCustomUpdate as codeblock) as logical

    local aLine as array
    local aField as array
    local aIncProcStep as array

    local aFieldsDef:=array(0) as array

    local aSourceTmpFields as array
    local aSourceTmpFldStruct as array

    local aTargetStruct:=(cAlias)->(dbStruct()) as array
    local aTargetFieldsDef as array
    local aReplicateValues as array
    local aNoReplicateValues as array
    local aTargetFieldsDefTmp as array
    local aTargetReplicateFields as array
    local aTargetReplicateFieldsPos as array
    local aTargetFieldsDefReplicate as array

    local aUpdateTableFields as array
    local aUpdateTableSource as array

    local bAddTLogReport as codeblock
    local bDeleteIfEmpty as codeblock
    local bAfterUpdateRecNo as codeblock
    local bAfterUpdateTable as codeblock
    local bUpdateMemoVirtual as codeblock
    local bTargetIgnoreFields as codeblock

    local bSourceSetFilter as codeblock
    local bEnableFilterBlock as codeblock
    local bEnableFilterBlockMem as codeblock

    local cError as character
    local cField as character
    local cLineUTF8 as character

    local cSourceAlias:=getNextAlias() as character
    local cTargetAlias:=cAlias as character
    local cTargetIgnoreFields as character
    local cTargetAliasRealName as character

    local cType as character

    local cCHR128 as character
    local cCHR135 as character
    local cCHR144 as character
    local cCHR162 as character
    local cCHR163 as character
    local cCHR182 as character
    local cCHR194 as character
    local cCHR195 as character
    local cCHR198 as character
    local cCHR199 as character
    local cCHR201 as character
    local cCHR205 as character
    local cCHR214 as character
    local cCHR227 as character
    local cCHR231 as character
    local cCHR243 as character
    local cCHR250 as character

    local cLine as character
    local cRootPath as character
    local cDataPath as character
    local cSourceFile as character
    local cSourceTable as character

    local cNoReplicateValues as character

    local cDeleteIfEmpty:="" as character

    local cSVFilAnt:=&("cFilAnt") as character

    local cRecCount as character

    local cTime as character

    local cTLogGroup as character
    local cTLogDetail as character

    local cIndexID as character
    local cFieldFilial as character
    local cAliasxFilial as character

    local cIncProc as character
    local cTimeRemaining as character

    local cSeekTable as character
    local cSeekIndexKey as character
    local cSeekTableIndex as character
    local cAllSeekIndexKey as character
    local cUpdateTableFields as character
    local cUpdateTableSource as character

    local cFWTemporaryTableRealName as character

    local cFieldsFilterBlock as character

    local lLock as logical
    local lFound as logical
    local lAddNew as logical
    local lAppend as logical
    local ldbCommit as logical
    local lHasError:=.F. as logical
    local lChkFilial as logical
    local lChkEncode as logical
    local lAskUpdate as logical
    local lSeekTable as logical
    local lImportData as logical
    local lMemoVirutal as logical
    local lAddFieldTmp as logical
    local lFilterBlock as logical
    local lCustomUpdate:=.F. as logical
    local lTypeReplicate:=.F. as logical
    local lDeleteIfEmpty as logical
    local lSeekTableFound as logical
    local lTypeReplicateRow as logical
    local lTablesEncodeUTF8 as logical
    local lAfterUpdateRecNo:=.F. as logical
    local lAppendIfNotExist as logical
    local lUpdateEmptyValue:=.F. as logical
    local lUpdateTableFields:=.F. as logical
    local lEnableFilterBlock as logical

    local nField as numeric
    local nFields as numeric

    local nReplicate as numeric
    local nReplicates:=0 as numeric

    local nEndLine as numeric
    local nStartLine as numeric

    local nRecProc:=0 as numeric
    local nRecCount as numeric
    local nRecProcPerc as numeric
    local nRecCountProc as numeric
    local nCommitBuffer as numeric
    local nRecProcCustom as numeric
    local nTargetFieldAT as numeric
    local nTargetFieldPos as numeric

    local nReplicateValuesAT as numeric

    local nIndexKey as numeric
    local nSeekTableIndex as numeric
    local nUpdateTableSource as numeric

    local nFieldFilial as numeric

    local nIncProcStep as numeric

    local nDeleteIfEmpty:=0 as numeric

    local nft_fRecNo as numeric
    local nft_fHandle as numeric

    local nDBS_ALEN:=(DBS_ALEN+1) as numeric

    local nMLCountSize:=150 as numeric

    local nAliasdbCount:=0 as numeric

    local nTmpAliasOrder as numeric
    local nTmpAliasNextRecNo:=(-1) as numeric

    local oFT as object
    local oTFIni as object
    local oProgress as object

    local oTimeRemaining as object

    local oFWTemporaryTable as object

    local oHMMemoVirutal as object

    local oHMIncProcStep as object

    local oHMTargetStruct as object
    local oHMTargetFieldsPos as object
    local oHMTargetFieldsDef as object
    local oHMTargetReplicateFields as object

    local oHMSourceFieldsDef as object

    begin sequence

        dfv():Default(@lPreLoadTable,.F.)

        nIndexKey:=retOrder(cTargetAlias,cIndexKey,(!lPreLoadTable))

        lImportData:=((lPreLoadTable).or.(nIndexKey!=0))
        if (!lImportData)
            ApMsgAlert("Unlocalized "+cTargetAlias+" table search index ("+cIndexKey+")")
            break
        endif

        oTFIni:=GetValue("readIniFile")

        cFieldFilial:=PrefixoCpo(cTargetAlias)
        cFieldFilial+="_FILIAL"

        lChkFilial:=(allTrim(oTFIni:GetPropertyValue(cTableImport,"ChkFilial","1"))=="1")
        cAliasxFilial:=xFilial(cTargetAlias)

        lAskUpdate:=(allTrim(oTFIni:GetPropertyValue(cTableImport,"AskUpdate","1"))=="1")
        if ((lAskUpdate).and.(cTargetAlias==cTableImport))
            if (lChkFilial)
                nFieldFilial:=(cTargetAlias)->(FieldPos(cFieldFilial))
                if (left(cIndexKey,Len(cFieldFilial))==cFieldFilial)
                    (cTargetAlias)->(dbSetOrder(nIndexKey))
                    (cTargetAlias)->(dbSeek(cAliasxFilial,.T.))
                else
                    (cTargetAlias)->(dbGoTop())
                endif
            endif
            MsProcess():MsAguarde({||nAliasdbCount:=datasul2totvs.GetRecCount(RetSQLName(cTargetAlias),"D_E_L_E_T_=' '")})
            if (nAliasdbCount>0)
                lImportData:=ApMsgNoYes("There is already data in this table. Do you want to update them?","Info")
                if (!lImportData)
                    break
                endif
            endif
        endif

        cSourceTable:=allTrim(oTFIni:GetPropertyValue("TablesImport",cTableImport,""))
        lImportData:=(!empty(cSourceTable))
        if (!lImportData)
            ApMsgAlert("There is no setting for the "+cSourceTable+" table","Attention")
            break
        endif

        cDataPath:=allTrim(oTFIni:GetPropertyValue("Tables","TablesData",""))
        lImportData:=(!empty(cDataPath))
        if (!lImportData)
            ApMsgAlert("Invalida Data Path ("+cDataPath+")","Attention")
            break
        endif

        cRootPath:=GetValue("cRootPath")
        cSourceFile:=(cRootPath+".."+cDataPath+cSourceTable+".csv")
        lImportData:=file(cSourceFile)
        if (!lImportData)
            ApMsgAlert("File ("+cSourceFile+") not found","Attention")
            break
        endif

        aFieldsDef:=aClone(GetValue(cSourceTable,aFieldsDef))
        lImportData:=(!empty(aFieldsDef))
        if (!lImportData)
            ApMsgAlert("Field definitions for the "+cSourceTable+" table not found","Attention")
            break
        endif

        lTypeReplicate:=GetValue(cSourceTable+"_TypeReplicate",lTypeReplicate)
        if (lTypeReplicate)
            lTypeReplicateRow:=(Lower(allTrim(oTFIni:GetPropertyValue(cSourceTable,"TypeReplicate","")))=="row")
        endif

        oHMSourceFieldsDef:=THashMap():New()
        nFields:=Len(aFieldsDef)
        for nField:=1 to nFields
            oHMSourceFieldsDef:Set(aFieldsDef[nField][DTS_DBS_NAME],aFieldsDef[nField][DTS_DBS_TYPE])
            oHMSourceFieldsDef:Set(aFieldsDef[nField][DTS_DBS_NAME]+"_AT",nField)
        next nField

        aTargetFieldsDef:=aClone(oTFIni:GetAllProperties(cSourceTable))
        lImportData:=(!empty(aFieldsDef))
        if (!lImportData)
            ApMsgAlert("Field definitions for the "+cTableImport+" table not found","Attention")
            break
        endif

        lAddFieldTmp:=(val(allTrim(oTFIni:GetPropertyValue(cTableImport,"addTmpField","0")))==1)
        if (lAddFieldTmp)
            cTmpFields:=allTrim(oTFIni:GetPropertyValue(cTableImport+"_addTmpField","TmpFields",""))
            lAddFieldTmp:=(!Empty(cTmpFields))
            if (lAddFieldTmp)
                aSourceTmpFields:=strToKArr2(cTmpFields,",")
                nFields:=Len(aSourceTmpFields)
                if (nFields>0)
                    aSourceTmpFldStruct:=array(0)
                    for nField:=1 to nFields
                        cField:=aSourceTmpFields[nField]
                        aAdd(aSourceTmpFldStruct,array(DBS_ALEN))
                        aSourceTmpFldStruct[nField][DBS_NAME]:=Upper(allTrim(oTFIni:GetPropertyValue(cField,"DBS_NAME","")))
                        aSourceTmpFldStruct[nField][DBS_TYPE]:=Upper(allTrim(oTFIni:GetPropertyValue(cField,"DBS_TYPE","")))
                        aSourceTmpFldStruct[nField][DBS_LEN]:=val(allTrim(oTFIni:GetPropertyValue(cField,"DBS_LEN","1")))
                        aSourceTmpFldStruct[nField][DBS_DEC]:=val(allTrim(oTFIni:GetPropertyValue(cField,"DBS_DEC","0")))
                    next nField
                endif
                FWFreeArray(@aSourceTmpFields)
            endif
        endif

        lMemoVirutal:=(allTrim(oTFIni:GetPropertyValue(cTableImport,"MemoVirtual","0"))=="1")
        if (lMemoVirutal)
            oHMMemoVirutal:=THashMap():New()
        endif

        if (lMemoVirutal)
            nFields:=Len(aTargetStruct)
            for nField:=1 to nFields
                cField:=aTargetStruct[nField][DBS_NAME]
                if (allTrim(oTFIni:GetPropertyValue(cField,"MemoVirtual","0"))=="1")
                    bUpdateMemoVirtual:=&(allTrim(oTFIni:GetPropertyValue(cField,"bUpdateMemoVirtual","{||}")))
                    oHMMemoVirutal:Set(cField,bUpdateMemoVirtual)
                endif
            next nField
        endif

        if (lAddFieldTmp)
            aEval(aSourceTmpFldStruct,{|e|aAdd(aTargetStruct,aClone(e))})
        endif

        oHMTargetStruct:=aUtils():dbStructHM(@aTargetStruct)

        nFields:=Len(aTargetFieldsDef)

        cTargetIgnoreFields:=allTrim(oTFIni:GetPropertyValue(cTableImport,"bTargetIgnoreFields",""))
        if (!empty(cTargetIgnoreFields))
            bTargetIgnoreFields:=&(cTargetIgnoreFields)
            aTargetFieldsDefTmp:=array(0)
            for nField:=1 to nFields
                cField:=aTargetFieldsDef[nField][1]
                if (eval(bTargetIgnoreFields,cField))
                    loop
                endif
                aAdd(aTargetFieldsDefTmp,aClone(aTargetFieldsDef[nField]))
            next nField
            aSize(aTargetFieldsDef,0)
            aEval(aTargetFieldsDefTmp,{|e|aAdd(aTargetFieldsDef,aClone(e))})
            FWFreeArray(@aTargetFieldsDefTmp)
            nFields:=Len(aTargetFieldsDef)
        endif

        if (lTypeReplicate)
            cNoReplicateValues:=allTrim(oTFIni:GetPropertyValue(cTableImport,"NoReplicateValues",""))
            aNoReplicateValues:=strToKArr2(cNoReplicateValues,",")
            aTargetReplicateFields:=array(0)
            oHMTargetReplicateFields:=THashMap():New()
        endif

        oHMTargetFieldsPos:=THashMap():New()
        oHMTargetFieldsDef:=THashMap():New()

        for nField:=1 to nFields
            cField:=aTargetFieldsDef[nField][1]
            if (oHMTargetStruct:Get(cField,@aField))
                nTargetFieldPos:=aField[1][nDBS_ALEN]
            else
                nTargetFieldPos:=0
            endif
            oHMTargetFieldsPos:Set(cField,nTargetFieldPos)
            oHMTargetFieldsDef:Set(cField,nField)
            aAdd(aTargetFieldsDef[nField],nTargetFieldPos)
            if (lTypeReplicate).and.(nTargetFieldPos>0)
                aAdd(aTargetReplicateFields,cField)
                oHMTargetReplicateFields:Set(cField,Len(aTargetReplicateFields))
            endif
        next nField

        oHMTargetStruct:Clean()
        oHMTargetStruct:=FreeObj(oHMTargetStruct)

        lEnableFilterBlock:=(allTrim(oTFIni:GetPropertyValue(cTableImport,"EnableFilterBlock","0"))=="1")
        if (lEnableFilterBlock)
            bEnableFilterBlock:=GetValue(cTableImport+"EnableFilterBlock",{||.T.})
            cFieldsFilterBlock:=allTrim(oTFIni:GetPropertyValue(cTableImport,"FieldsFilterBlock",""))
            bEnableFilterBlockMem:=GetValue(cTableImport+"EnableFilterBlockMem",{||.T.})
        endif

        oFT:=uft():New()
        if (valtype(GetValue(cTableImport+"SourceSetFilter",nil))=="B")
            bSourceSetFilter:=GetValue(cTableImport+"SourceSetFilter")
            oFT:ft_fSetFilter(bSourceSetFilter)
        endif

        MsProcess():MsAguarde({||nft_fHandle:=oFT:ft_fUse(cSourceFile)},"Wait. Loading Data File.","Loading:["+cSourceFile+"]")

        lImportData:=(nft_fHandle>=0)
        if (!lImportData)
            ApMsgAlert("Could not open the file: "+cSourceFile,"Attention")
            break
        endif

        lImportData:=(Len(aTargetStruct)>=0)
        if (!lImportData)
            ApMsgAlert("Could not get structure for table:  "+cTableImport,"Attention")
            break
        endif

        oFWTemporaryTable:=FWTemporaryTable():New(@cSourceAlias,@aTargetStruct)
        oFWTemporaryTable:AddIndex("01",aAddIndex)
        oFWTemporaryTable:Create()

        SetValue("import"+cTableImport+"Alias",cSourceAlias)
        SetValue("import"+cTableImport+"FWTemporaryTable",oFWTemporaryTable)

        cFWTemporaryTableRealName:=oFWTemporaryTable:getRealName()
        SetValue("import"+cTableImport+"Table",cFWTemporaryTableRealName)

        FWFreeArray(@aField)
        FWFreeArray(@aTargetStruct)

        lChkEncode:=(allTrim(oTFIni:GetPropertyValue(cTableImport,"ChkEncode","0"))=="1")
        if (lChkEncode)
            cCHR128:=chr(128)
            cCHR135:=chr(135)
            cCHR144:=chr(144)
            cCHR162:=chr(162)
            cCHR163:=chr(163)
            cCHR182:=chr(182)
            cCHR194:=chr(194)
            cCHR195:=chr(195)
            cCHR198:=chr(198)
            cCHR199:=chr(199)
            cCHR201:=chr(201)
            cCHR205:=chr(205)
            cCHR214:=chr(214)
            cCHR227:=chr(227)
            cCHR231:=chr(231)
            cCHR243:=chr(243)
            cCHR250:=chr(250)
        endif

        bAddTLogReport:=&(allTrim(oTFIni:GetPropertyValue(cTableImport,"bAddTLogReport","{|cAlias,cTableImport,oTLogReport|.F.}")))
        bDeleteIfEmpty:=&(allTrim(oTFIni:GetPropertyValue(cTableImport,"bDeleteIfEmpty","{|cAlias|.F.}")))

        lSeekTable:=(!empty(cSeekTable:=allTrim(oTFIni:GetPropertyValue(cTableImport,"seekTable",""))))
        if (lSeekTable)
            lSeekTable:=chkFile(cSeekTable)
            if (lSeekTable)
                cSeekIndexKey:=allTrim(oTFIni:GetPropertyValue(cTableImport,"seekIndexKey",""))
                cSeekTableIndex:=allTrim(oTFIni:GetPropertyValue(cTableImport,"seekTableIndex",""))
                nSeekTableIndex:=retOrder(cSeekTable,cSeekTableIndex,.T.)
                lSeekTable:=(nSeekTableIndex>0)
                if (lSeekTable)
                    (cSeekTable)->(dbSetOrder(nSeekTableIndex))
                    cUpdateTableFields:=allTrim(oTFIni:GetPropertyValue(cTableImport,"updateTableFields",""))
                    aUpdateTableFields:=strToKArr2(cUpdateTableFields,",")
                    cUpdateTableSource:=allTrim(oTFIni:GetPropertyValue(cTableImport,"updateTableSource",""))
                    aUpdateTableSource:=strToKArr2(cUpdateTableSource,",")
                    nUpdateTableSource:=len(aUpdateTableFields)
                    lUpdateTableFields:=((nUpdateTableSource>0).and.(nUpdateTableSource==len(aUpdateTableSource)))
                endif
            endif
        endif

        nIncProcStep:=Int(val(allTrim(oTFIni:GetPropertyValue(cTableImport,"IncProcStep","0"))))
        if (empty(nIncProcStep))
            nIncProcStep:=Int(val(allTrim(oTFIni:GetPropertyValue("General","IncProcStep","1"))))
        endif
        nIncProcStep:=Min(Max(nIncProcStep,1),1000)

        lTablesEncodeUTF8:=(allTrim(oTFIni:GetPropertyValue("General","TablesEncodeUTF8","0"))=="1")

        begin sequence

            nStartLine:=GetValue(cTableImport+"StartLine",1)
            if (nStartLine==1)
                nStartLine:=val(allTrim(oTFIni:GetPropertyValue(cTableImport,"StartLine","1")))
            endif

            nRecCount:=oFT:ft_fLastRec()

            nEndLine:=GetValue(cTableImport+"EndLine",nRecCount)
            if (nEndLine>=nRecCount)
                nEndLine:=val(allTrim(oTFIni:GetPropertyValue(cTableImport,"EndLine",cTools():NToS(nRecCount))))
            endif
            nRecCount:=Min(nRecCount,nEndLine)

            if (nStartLine>1)
                nRecCount:=((nRecCount-nStartLine)+1)
                oFT:ft_fGoTo(nStartLine)
            else
                oFT:ft_fGoTop()
            endif

            nRecCountProc:=nRecCount

            if ((lPercentage).and.(nRecCount>=1000))
                nIncProcStep=(1/nRecCount*100)
                nRecCount:=200
                aIncProcStep:=array(nRecCount,2)
                aEval(aIncProcStep,{|x,y|aIncProcStep[y][2]:=((y*5)/100),aIncProcStep[y][1]:=Round((nRecCountProc*aIncProcStep[y][2]),0)})
                oHMIncProcStep:=aToHM(aIncProcStep)
                FWFreeArray(@aIncProcStep)
            else
                lPercentage:=.F.
                if (nRecCount<=nIncProcStep)
                    nIncProcStep:=1
                endif
            endif

            cRecCount:=cTools():NToS(nRecCountProc)

            oMsNewProcess:SetRegua1(if(lPercentage,nRecCount,Round(nRecCount/nIncProcStep,0)))

            oTimeRemaining:=timeRemaining():New(nRecCountProc)

            oProgress:=txtProgress():New()

            TCSrvMap(cSourceAlias,nil,.F.)

            while (!oFT:ft_fEof())

                nft_fRecNo:=oFT:ft_fRecNo()
                cLine:=oFT:ft_fReadLN()

                begin sequence

                    if (empty(cLine))
                        break
                    endif

                    if (lChkEncode)
                        if (lTablesEncodeUTF8)
                            cLineUTF8:=DecodeUTF8(cLine)
                        else
                            cLineUTF8:=""
                        endif
                        if (empty(cLineUTF8))
                            cLine:=cTools():StrReplace(;
                                cLine,;
                                {cCHR144,cCHR201},;
                                {cCHR214,cCHR205},;
                                {cCHR199,cCHR195},;
                                {cCHR128,cCHR199},;
                                {cCHR182,cCHR194},;
                                {cCHR135,cCHR231},;
                                {cCHR198,cCHR227},;
                                {cCHR162,cCHR243},;
                                {cCHR163,cCHR250};
                            )
                        else
                            cLine:=cLineUTF8
                            cLineUTF8:=""
                        endif
                    endif

                    aLine:=strTokArr2(cLine,";")

                    lAppend:=.T.

                    if ((lChkFilial).or.(lEnableFilterBlock).or.(lAddFieldTmp))

                        for nField:=1 to nFields
                            cField:=aTargetFieldsDef[nField][1]
                            if (;
                                    (;
                                        (lChkFilial).and.(cField==cFieldFilial);
                                    ).or.;
                                    (;
                                        (lEnableFilterBlock).and.(cField$cFieldsFilterBlock);
                                    ).or.;
                                    (;
                                        (lAddFieldTmp).and.(aScan(aAddIndex,{|e|(e==cField)})>0);
                                    );
                                )
                                lHasError:=.F.
                                xValue:=(cSourceAlias)->(;
                                    getTargetFieldValue(;
                                        @lHasError,;
                                        @oTFIni,;
                                        @aLine,;
                                        @cField,;
                                        aTargetFieldsDef[nField],;
                                        @aFieldsDef,;
                                        @oHMSourceFieldsDef;
                                    );
                                )
                                if (lHasError)
                                    cError:=EvalBlockGetValue("ErrorDescription","")
                                    cError+=EvalBlockGetValue("ErrorStack","")
                                    DelSection("EvalBlock")
                                    if (!empty(cError))
                                        cTLogDetail:=cTools():StrReplace(cError,{CRLF," "})
                                        cError:=""
                                        cTLogGroup:="table : ["+cSourceFile+"] foram Encontradas inconsistencias na linha ["+cTools():NToS(nft_fRecNo)+"]:"
                                        oTLogReport:AddGroup(cTLogGroup)
                                        oTLogReport:AddDetail(cTLogGroup,cTLogDetail,nMLCountSize)
                                        cTLogDetail:=""
                                        oTLogReport:AddDetail(cTLogGroup,cLine,nMLCountSize)
                                        lEnd:=oMsNewProcess:lEnd:=.T.
                                        lAppend:=.F.
                                        break
                                    endif
                                endif
                                if (empty(xValue))
                                    if (lHasError)
                                        cTLogGroup:="table : ["+cSourceFile+"] foram Encontradas inconsistencias na linha ["+cTools():NToS(nft_fRecNo)+"]:"
                                        oTLogReport:AddGroup(cTLogGroup)
                                        cTLogDetail:="Estrutura da Linha diferente da estrutura de Dados"
                                        oTLogReport:AddDetail(cTLogGroup,cTLogDetail)
                                        oTLogReport:AddDetail(cTLogGroup,cLine,nMLCountSize)
                                    endif
                                    lAppend:=.F.
                                    exit
                                endif
                            endif
                            if ((lChkFilial).and.(cField==cFieldFilial))
                                SetFilAnt(xValue)
                            endif
                            if ((lEnableFilterBlock).and.(cField$cFieldsFilterBlock))
                                lHasError:=(!EvalBlock():EvalBlock({||lAppend:=(Eval(bEnableFilterBlockMem,xValue,cField))},nil,.F.,nil,nil))
                                if (lHasError)
                                    cError:=EvalBlockGetValue("ErrorDescription","")
                                    cError+=EvalBlockGetValue("ErrorStack","")
                                    DelSection("EvalBlock")
                                    if (!empty(cError))
                                        cTLogDetail:=cTools():StrReplace(cError,{CRLF," "})
                                        cError:=""
                                        cTLogGroup:="table : ["+cSourceFile+"] foram Encontradas inconsistencias na linha ["+cTools():NToS(nft_fRecNo)+"]:"
                                        oTLogReport:AddGroup(cTLogGroup)
                                        oTLogReport:AddDetail(cTLogGroup,cTLogDetail,nMLCountSize)
                                        cTLogDetail:=""
                                        oTLogReport:AddDetail(cTLogGroup,cLine,nMLCountSize)
                                        cError:=""
                                    endif
                                endif
                                if (!lAppend)
                                    exit
                                endif
                            endif
                        next nField

                    endif

                    if (lEnd)
                        break
                    endif

                    if (lAppend)

                        (cSourceAlias)->(dbAppend(.F.))

                        ldbCommit:=(++nCommitBuffer>=1024)

                        if (lSeekTable)
                            cAllSeekIndexKey:=cSeekIndexKey
                        endif

                        for nField:=1 to nFields

                            cField:=aTargetFieldsDef[nField][1]

                            if (lTypeReplicate)
                                nReplicates:=GetValue(aTargetFieldsDef[nField][2]+"_TypeReplicate",0)
                                if (nReplicates>0)
                                    lTypeReplicate:=.F.
                                endif
                            endif

                            if ((!lChkFilial).and.(cField==cFieldFilial))

                                xValue:=cAliasxFilial

                            else

                                if ((nReplicates>0).and.(!lTypeReplicateRow).and.(GetValue(aTargetFieldsDef[nField][2]+"_TypeReplicate",0)>0))

                                    nReplicate:=0

                                    while (((++nReplicate)<=nReplicates))

                                        lHasError:=.F.

                                        if (nReplicate==1)

                                            xValue:=(cSourceAlias)->(getTargetFieldValue(@lHasError,@oTFIni,@aLine,@cField,aTargetFieldsDef[nField],@aFieldsDef,@oHMSourceFieldsDef))

                                        else

                                            aTargetFieldsDefReplicate:=aClone(aTargetFieldsDef[nField])
                                            aTargetFieldsDefReplicate[2]+=cTools():NToS(nReplicate)

                                            xValue:=(cSourceAlias)->(getTargetFieldValue(@lHasError,@oTFIni,@aLine,@cField,@aTargetFieldsDefReplicate,@aFieldsDef,@oHMSourceFieldsDef))

                                            FWFreeArray(@aTargetFieldsDefReplicate)

                                        endif

                                        if (lHasError)

                                            cError:=EvalBlockGetValue("ErrorDescription","")
                                            cError+=EvalBlockGetValue("ErrorStack","")
                                            DelSection("EvalBlock")

                                            if (!empty(cError))
                                                cTLogDetail:=cTools():StrReplace(cError,{CRLF," "})
                                                cError:=""
                                                cTLogGroup:="table : ["+cSourceFile+"] foram Encontradas inconsistencias na linha ["+cTools():NToS(nft_fRecNo)+"]:"
                                                oTLogReport:AddGroup(cTLogGroup)
                                                oTLogReport:AddDetail(cTLogGroup,cTLogDetail,nMLCountSize)
                                                cTLogDetail:=""
                                                oTLogReport:AddDetail(cTLogGroup,cLine,nMLCountSize)
                                                lEnd:=oMsNewProcess:lEnd:=.T.
                                                lAppend:=.F.
                                                break
                                            endif

                                        endif

                                        if ((!oHMTargetFieldsPos:Get(cField,@nTargetFieldPos)).or.(nTargetFieldPos==0))
                                            loop
                                        endif

                                        (cSourceAlias)->(FieldPut(nTargetFieldPos,xValue))

                                    end while

                                    loop

                                else

                                    lHasError:=.F.

                                    xValue:=(cSourceAlias)->(getTargetFieldValue(@lHasError,@oTFIni,@aLine,@cField,aTargetFieldsDef[nField],@aFieldsDef,@oHMSourceFieldsDef))

                                endif

                                if (lHasError)

                                    cError:=EvalBlockGetValue("ErrorDescription","")
                                    cError+=EvalBlockGetValue("ErrorStack","")
                                    DelSection("EvalBlock")

                                    if (!empty(cError))
                                        cTLogDetail:=cTools():StrReplace(cError,{CRLF," "})
                                        cError:=""
                                        cTLogGroup:="table : ["+cSourceFile+"] foram Encontradas inconsistencias na linha ["+cTools():NToS(nft_fRecNo)+"]:"
                                        oTLogReport:AddGroup(cTLogGroup)
                                        oTLogReport:AddDetail(cTLogGroup,cTLogDetail,nMLCountSize)
                                        oTLogReport:AddDetail(cTLogGroup,cLine,nMLCountSize)
                                        cTLogDetail:=""
                                        lEnd:=oMsNewProcess:lEnd:=.T.
                                        lAppend:=.F.
                                        break
                                    endif

                                endif

                            endif

                            if (empty(xValue))
                                if (lHasError)
                                    cTLogGroup:="table : ["+cSourceFile+"] foram Encontradas inconsistencias na linha ["+cTools():NToS(nft_fRecNo)+"]:"
                                    oTLogReport:AddGroup(cTLogGroup)
                                    cTLogDetail:="Estrutura da Linha diferente da estrutura de Dados"
                                    oTLogReport:AddDetail(cTLogGroup,cTLogDetail)
                                    oTLogReport:AddDetail(cTLogGroup,cLine,nMLCountSize)
                                    lHasError:=(!EvalBlock():EvalBlock({||lDeleteIfEmpty:=((cSourceAlias)->(Eval(bDeleteIfEmpty,cSourceAlias)))},nil,.F.,nil,nil))
                                    if (lDeleteIfEmpty)
                                        (cSourceAlias)->(dbDelete())
                                        cDeleteIfEmpty+=(cSourceAlias)->(cTools():NToS(RecNo()))
                                        cDeleteIfEmpty+=","
                                        nDeleteIfEmpty++
                                        break
                                    endif
                                    exit
                                endif
                                if (!lUpdateEmptyValue)
                                    loop
                                endif
                            endif

                            if ((!oHMTargetFieldsPos:Get(cField,@nTargetFieldPos)).or.(nTargetFieldPos==0))
                                loop
                            endif

                            (cSourceAlias)->(FieldPut(nTargetFieldPos,xValue))

                            if ((lSeekTable).and.(!empty(cAllSeekIndexKey)))
                                if (cField$cAllSeekIndexKey)
                                    cAllSeekIndexKey:=cTools():StrReplace(cAllSeekIndexKey,{cField,""})
                                endif
                                if (empty(cTools():StrReplace(cAllSeekIndexKey,{"+",""})))
                                    cAllSeekIndexKey:=""
                                    lSeekTableFound:=(cSeekTable)->(MsSeek((cSourceAlias)->(&(cSeekIndexKey)),.F.))
                                endif
                            endif

                        next nField

                        lHasError:=(!EvalBlock():EvalBlock({||(cSourceAlias)->(Eval(bAddTLogReport,cSourceAlias,cTableImport,oTLogReport))},nil,.F.,nil,nil))

                        lHasError:=(!EvalBlock():EvalBlock({||lDeleteIfEmpty:=((cSourceAlias)->(Eval(bDeleteIfEmpty,cSourceAlias)))},nil,.F.,nil,nil))
                        if (lDeleteIfEmpty)
                            (cSourceAlias)->(dbDelete())
                            cDeleteIfEmpty+=(cSourceAlias)->(cTools():NToS(RecNo()))
                            cDeleteIfEmpty+=","
                            nDeleteIfEmpty++
                            break
                        endif

                        if (lEnableFilterBlock)
                            lHasError:=(!EvalBlock():EvalBlock({||lFilterBlock:=(cSourceAlias)->(!Eval(bEnableFilterBlock,cSourceAlias))},nil,.F.,nil,nil))
                            if ((!lHasError).and.(lFilterBlock))
                                (cSourceAlias)->(dbDelete())
                                cDeleteIfEmpty+=(cSourceAlias)->(cTools():NToS(RecNo()))
                                cDeleteIfEmpty+=","
                                nDeleteIfEmpty++
                                break
                            endif
                        endif

                        if (lSeekTable)

                            lSeekTableFound:=(cSeekTable)->(MsSeek((cSourceAlias)->(&(cSeekIndexKey)),.F.))

                            if (lSeekTableFound)

                                if ((lUpdateTableFields).and.(lLock:=MySoftLock(cSeekTable)))

                                    lLock:=(cSeekTable)->(MyRecLock(cSeekTable,.F.))

                                    if (lLock)

                                        for nField:=1 to nUpdateTableSource

                                            cField:=aUpdateTableSource[nField]

                                            if ((oHMTargetFieldsDef:Get(cField,@nTargetFieldAT)).and.(nTargetFieldAT>0))

                                                lHasError:=.F.
                                                xValue:=(cSourceAlias)->(getTargetFieldValue(@lHasError,@oTFIni,@aLine,@cField,aTargetFieldsDef[nTargetFieldAT],@aFieldsDef,@oHMSourceFieldsDef,@cType))

                                                if (lHasError)

                                                    cError:=EvalBlockGetValue("ErrorDescription","")
                                                    cError+=EvalBlockGetValue("ErrorStack","")
                                                    DelSection("EvalBlock")

                                                    if (!empty(cError))
                                                        cTLogDetail:=cTools():StrReplace(cError,{CRLF," "})
                                                        cError:=""
                                                        cTLogGroup:="table : ["+cSourceFile+"] foram Encontradas inconsistencias na linha ["+cTools():NToS(nft_fRecNo)+"]:"
                                                        oTLogReport:AddGroup(cTLogGroup)
                                                        oTLogReport:AddDetail(cTLogGroup,cTLogDetail,nMLCountSize)
                                                        cTLogDetail:=""
                                                        lEnd:=oMsNewProcess:lEnd:=.T.
                                                        break
                                                    endif

                                                endif

                                                cField:=aUpdateTableFields[nField]
                                                xValue:=NormalizeData(@lHasError,xValue,cType,cField,.T.,@st_oHMbTransform,@oTFIni)

                                                if (lHasError)

                                                    cError:=EvalBlockGetValue("ErrorDescription","")
                                                    cError+=EvalBlockGetValue("ErrorStack","")
                                                    DelSection("EvalBlock")

                                                    if (!empty(cError))
                                                        cTLogDetail:=cTools():StrReplace(cError,{CRLF," "})
                                                        cError:=""
                                                        cTLogGroup:="table : ["+cSourceFile+"] foram Encontradas inconsistencias na linha ["+cTools():NToS(nft_fRecNo)+"]:"
                                                        oTLogReport:AddGroup(cTLogGroup)
                                                        oTLogReport:AddDetail(cTLogGroup,cTLogDetail,nMLCountSize)
                                                        cTLogDetail:=""
                                                        lEnd:=oMsNewProcess:lEnd:=.T.
                                                        (cSeekTable)->(MsUnLock())
                                                        break
                                                    endif

                                                endif

                                            endif

                                            (cSeekTable)->(FieldPut(FieldPos(cField),xValue))

                                        next nField

                                        (cSeekTable)->(MsUnLock())

                                    endif

                                endif

                            endif

                        endif

                        if ((nReplicates>0).and.(lTypeReplicateRow))

                            aReplicateValues:=(cSourceAlias)->(aUtils():RegToArray(cSourceAlias,recNo(),aTargetReplicateFields,.F.,.F.,@aTargetReplicateFieldsPos))
                            nReplicate:=1

                            while (((++nReplicate)<=nReplicates))

                                lAppend:=.T.

                                (cSourceAlias)->(dbAppend(.F.))
                                ldbCommit:=(++nCommitBuffer>=1024)

                                for nField:=1 to nFields

                                    cField:=aTargetFieldsDef[nField][1]

                                    if (GetValue(aTargetFieldsDef[nField][2]+"_TypeReplicate",0)>0)

                                        aTargetFieldsDefReplicate:=aClone(aTargetFieldsDef[nField])
                                        aTargetFieldsDefReplicate[2]+=cTools():NToS(nReplicate)
                                        xValue:=(cSourceAlias)->(getTargetFieldValue(@lHasError,@oTFIni,@aLine,@cField,@aTargetFieldsDefReplicate,@aFieldsDef,@oHMSourceFieldsDef))

                                        FWFreeArray(@aTargetFieldsDefReplicate)

                                    else

                                        if (!oHMTargetReplicateFields:Get(cField,@nReplicateValuesAT))
                                            loop
                                        endif

                                        if (aScan(aNoReplicateValues,{|x|(x==cField)})==0)
                                            xValue:=aReplicateValues[nReplicateValuesAT]
                                        else
                                            xValue:=(cSourceAlias)->(getTargetFieldValue(@lHasError,@oTFIni,@aLine,@cField,aTargetFieldsDef[nField],@aFieldsDef,@oHMSourceFieldsDef,@cType))
                                        endif

                                    endif

                                    if ((lEnableFilterBlock).and.(cField$cFieldsFilterBlock))
                                        lHasError:=(!EvalBlock():EvalBlock({||lAppend:=(Eval(bEnableFilterBlockMem,xValue,cField))},nil,.F.,nil,nil))
                                        if ((!lHasError).and.(!lAppend))
                                            (cSourceAlias)->(dbDelete())
                                            cDeleteIfEmpty+=(cSourceAlias)->(cTools():NToS(RecNo()))
                                            cDeleteIfEmpty+=","
                                            nDeleteIfEmpty++
                                            exit
                                        endif
                                    endif

                                    if ((!oHMTargetFieldsPos:Get(cField,@nTargetFieldPos)).or.(nTargetFieldPos==0))
                                        loop
                                    endif

                                    (cSourceAlias)->(FieldPut(nTargetFieldPos,xValue))

                                next nField

                                if (lAppend)
                                    lHasError:=(!EvalBlock():EvalBlock({||lDeleteIfEmpty:=((cSourceAlias)->(Eval(bDeleteIfEmpty,cSourceAlias)))},nil,.F.,nil,nil))
                                    if (lDeleteIfEmpty)
                                        (cSourceAlias)->(dbDelete())
                                        cDeleteIfEmpty+=(cSourceAlias)->(cTools():NToS(RecNo()))
                                        cDeleteIfEmpty+=","
                                        nDeleteIfEmpty++
                                    endif
                                endif

                                if ((nDeleteIfEmpty>=1024).or.((ldbCommit).and.(nDeleteIfEmpty>0)))
                                    if (!ldbCommit)
                                        (cSourceAlias)->(dbCommitAll())
                                    endif
                                    if (right(cDeleteIfEmpty,1)==",")
                                        cDeleteIfEmpty:=subStr(cDeleteIfEmpty,1,(Len(cDeleteIfEmpty)-1))
                                    endif
                                    nDeleteIfEmpty:=TCSQLExec("DELETE FROM "+cFWTemporaryTableRealName+" WHERE R_E_C_N_O_ IN ("+cDeleteIfEmpty+")")
                                    cDeleteIfEmpty:=""
                                    nDeleteIfEmpty:=0
                                    TCRefresh(cFWTemporaryTableRealName)
                                endif

                            end while

                            FwFreeArray(@aReplicateValues)

                        endif

                    endif

                end sequence

                cLine:=""
                FWFreeArray(@aLine)

                nRecProc++
                if (lPercentage)
                    nRecProcPerc:=(nRecProc*nIncProcStep)
                else
                    nRecProcPerc:=nRecProc
                endif

                oTimeRemaining:nProgress:=nRecProc

                if ((if(lPercentage,(oHMIncProcStep:Get(nRecProc)),(Mod(nRecProcPerc,nIncProcStep)==0))).or.(nRecProcPerc>=nRecCount))
                    oTimeRemaining:Calcule(.F.)
                    cTimeRemaining:=" :: End of processing in ["+oTimeRemaining:GetcTRemaining()+"]["+DtoC(oTimeRemaining:GetdEndTime())+"]"
                    cTimeRemaining+="["+oTimeRemaining:GetcEndTime()+"]"
                    cTimeRemaining+="["+oTimeRemaining:GetcAverageTime()+"]"
                    cIncProc:="["+oProgress:Eval()+"] "
                    cIncProc+="Processing Record: "
                    cIncProc+=cTools():NToS(nRecProc)
                    cIncProc+="/"
                    cIncProc+=cRecCount
                    cIncProc+=cTimeRemaining
                    cIncProc+="::["+cTools():NToS(if((nRecProcPerc>=nRecCount),100,((nRecProc/nRecCountProc)*100)))+"%]"
                    oMsNewProcess:IncRegua1(cIncProc)
                endif

                lEnd:=oMsNewProcess:lEnd

                if (lEnd)
                    cTLogGroup:="Process canceled by user:"
                    oTLogReport:AddGroup(cTLogGroup)
                    cTLogDetail:="Process canceled by user ["+DtoC(Date())+"]["+Time()+"]"
                    oTLogReport:AddDetail(cTLogGroup,cTLogDetail)
                    exit
                endif

                if (ldbCommit)
                    nCommitBuffer:=0
                    (cSourceAlias)->(dbCommitAll())
                endif

                if ((nDeleteIfEmpty>=1024).or.((ldbCommit).and.(nDeleteIfEmpty>0)))
                    if (!ldbCommit)
                        (cSourceAlias)->(dbCommitAll())
                    endif
                    if (right(cDeleteIfEmpty,1)==",")
                        cDeleteIfEmpty:=subStr(cDeleteIfEmpty,1,(Len(cDeleteIfEmpty)-1))
                    endif
                    nDeleteIfEmpty:=TCSQLExec("DELETE FROM "+cFWTemporaryTableRealName+" WHERE R_E_C_N_O_ IN ("+cDeleteIfEmpty+")")
                    cDeleteIfEmpty:=""
                    nDeleteIfEmpty:=0
                    TCRefresh(cFWTemporaryTableRealName)
                endif

                if (ldbCommit)
                    ldbCommit:=.F.
                endif

                if (nRecProcPerc>=nRecCount)
                    exit
                endif

                oFT:ft_fDelete()
                oFT:ft_fSkip()

            end while

            if (lPercentage)
                oHMIncProcStep:Clean()
                oHMIncProcStep:=FreeObj(oHMIncProcStep)
            endif

            cLine:=""
            FWFreeArray(@aLine)

            if (nCommitBuffer>0)
                (cSourceAlias)->(dbCommitAll())
            endif

            if (nDeleteIfEmpty>0)
                if (right(cDeleteIfEmpty,1)==",")
                    cDeleteIfEmpty:=subStr(cDeleteIfEmpty,1,(Len(cDeleteIfEmpty)-1))
                endif
                nDeleteIfEmpty:=TCSQLExec("DELETE FROM "+cFWTemporaryTableRealName+" WHERE R_E_C_N_O_ IN ("+cDeleteIfEmpty+")")
                cDeleteIfEmpty:=""
                nDeleteIfEmpty:=0
                TCRefresh(cFWTemporaryTableRealName)
            endif

            nDeleteIfEmpty:=TCSQLExec("DELETE FROM "+cFWTemporaryTableRealName+" WHERE D_E_L_E_T_='*'")
            TCRefresh(cFWTemporaryTableRealName)

            oFT:ft_fUse()
            oFT:FreeObj()
            oFT:=FreeObj(oFT)

            cTLogGroup:="["+cAlias+"/"+cTableImport+"]"

            cTLogDetail:="Data: ["+DToC(oTimeRemaining:GetdStartTime())+"]"
            cTLogDetail+=" "
            cTLogDetail+="Hora: ["+oTimeRemaining:GetcStartTime()+"]"
            cTLogDetail+=" : "
            cTLogDetail+="Inicio da Leitura/Processamento de Dados (Datasul)."
            oTLogReport:AddDetail(cTLogGroup,cTLogDetail)

            cTLogDetail:="Data: ["+DToC(oTimeRemaining:GetdEndTime())+"]"
            cTLogDetail+=" "
            cTLogDetail+="Hora: ["+oTimeRemaining:GetcEndTime()+"]"
            cTLogDetail+=" : "
            cTLogDetail+="Termino da Leitura/Processamento de Dados (Datasul)."
            oTLogReport:AddDetail(cTLogGroup,cTLogDetail)

            cTLogDetail:=oTLogReport:ThinLine()
            oTLogReport:AddDetail(cTLogGroup,cTLogDetail)

            cTLogDetail:="["+oTimeRemaining:GetcTimeDiff()+"]"
            cTLogDetail+=" : "
            cTLogDetail+="Tempo de Processamento Leitura/Processamento de Dados (Datasul).
            oTLogReport:AddDetail(cTLogGroup,cTLogDetail)

            cTLogDetail:="["+oTimeRemaining:GetcAverageTime()+"]"
            cTLogDetail+=" : "
            cTLogDetail+="Tempo Medio de Processamento Leitura/Processamento de Dados (Datasul).
            oTLogReport:AddDetail(cTLogGroup,cTLogDetail)

            cTLogDetail:=oTLogReport:ThinLine()
            oTLogReport:AddDetail(cTLogGroup,cTLogDetail)

            if ((lEnd).or.(lPreLoadTable))
                break
            endif

            if (allTrim(oTFIni:GetPropertyValue(cTableImport,"TCSQLUpdateTable","0"))=="1")
                cTargetAliasRealName:=RetSQLName(cTargetAlias)
                MsProcess():MsAguarde(;
                    {||;
                        datasul2totvs.TCSQLUpdateTable(;
                            cSourceAlias,;
                            cFWTemporaryTableRealName,;
                            cTargetAlias,;
                            cTargetAliasRealName,;
                            aTargetFieldsDef,;
                            aAddIndex,;
                            aSourceTmpFldStruct,;
                            oMsNewProcess,;
                            oTLogReport,;
                            oProgress;
                        );
                    },;
                    "Wait...",;
                    "Updating data from table "+cTargetAliasRealName;
                )
            endif

            MsProcess():MsAguarde({||nAliasdbCount:=datasul2totvs.GetRecCount(cFWTemporaryTableRealName)},"Wait...","Verifying record data for import")

            nRecCount:=Min(nAliasdbCount,(cSourceAlias)->(recCount()))

            nRecCountProc:=nRecCount

            if ((lPercentage).and.(nRecCount>=1000))
                nIncProcStep=(1/nRecCount*100)
                nRecCount:=200
                aIncProcStep:=array(nRecCount,2)
                aEval(aIncProcStep,{|x,y|aIncProcStep[y][2]:=((y*5)/100),aIncProcStep[y][1]:=Round((nRecCountProc*aIncProcStep[y][2]),0)})
                oHMIncProcStep:=aToHM(aIncProcStep)
                FWFreeArray(@aIncProcStep)
            else
                lPercentage:=.F.
                if (nRecCount<=nIncProcStep)
                    nIncProcStep:=1
                endif
            endif

            cRecCount:=cTools():NToS(nRecCountProc)

            oMsNewProcess:SetRegua2(if(lPercentage,nRecCount,Round(nRecCount/nIncProcStep,0)))

            oTimeRemaining:SetRemaining(nRecCountProc)
            if (nRecCountProc==0)
                oTimeRemaining:Calcule(.F.)
            endif

            (cTargetAlias)->(dbSetOrder(nIndexKey))

            nRecProc:=0

            lCustomUpdate:=((valType(bCustomUpdate)=="B").or.(allTrim(oTFIni:GetPropertyValue(cTableImport,"CustomUpdate","0"))=="1"))
            if (lCustomUpdate)
                if (valType(bCustomUpdate)!="B")
                    bCustomUpdate:=&(allTrim(oTFIni:GetPropertyValue(cTableImport,"bCustomUpdate","{|cSourceAlias,cAlias,lFound,lAddNew,cIndexKey,cIndexID,nFields,aTargetFieldsDef,oTLogReport|.F.}")))
                endif
            endif

            lAppendIfNotExist:=(allTrim(oTFIni:GetPropertyValue(cTableImport,"AppendIfNotExist","1"))=="1")
            lUpdateEmptyValue:=(allTrim(oTFIni:GetPropertyValue(cTableImport,"UpdateEmptyValue","0"))=="1")

            bAfterUpdateRecNo:=&(allTrim(oTFIni:GetPropertyValue(cTableImport,"bAfterUpdateRecNo","{|cAlias,nRecNo|.F.}")))
            lAfterUpdateRecNo:=(valType(bAfterUpdateRecNo)=="B")

            bAfterUpdateTable:=&(allTrim(oTFIni:GetPropertyValue(cTableImport,"bAfterUpdateTable","{|cAlias,oTLogReport,oMsNewProcess,oTimeRemaining,oProgress|.F.}")))

            (cSourceAlias)->(dbGoTop())

            nTmpAliasOrder:=(cSourceAlias)->(IndexOrd())

            while (cSourceAlias)->(!eof())
                if ((cSourceAlias)->(!dbEval():GetNextRecNo(@cSourceAlias,@nTmpAliasNextRecNo,@nTmpAliasOrder)))
                    exit
                endif
                cIndexID:=(cSourceAlias)->(&(cIndexKey))
                lFound:=(cTargetAlias)->(dbSeek(cIndexID,.F.))
                begin sequence
                    if ((!lFound).and.(!lAppendIfNotExist))
                        break
                    endif
                    lAddNew:=(!lFound)
                    nRecProcCustom:=1
                    if (lCustomUpdate)
                        lHasError:=(!EvalBlock():EvalBlock(;
                            {||(cTargetAlias)->(;
                                Eval(;
                                    @bCustomUpdate,;
                                    @cSourceAlias,;
                                    @cTargetAlias,;
                                    @lFound,;
                                    @lAddNew,;
                                    @cIndexKey,;
                                    @cIndexID,;
                                    @nFields,;
                                    @aTargetFieldsDef,;
                                    @oTLogReport,;
                                    @nTmpAliasNextRecNo,;
                                    @nTmpAliasOrder,;
                                    @nRecProcCustom;
                                );
                            )},;
                            nil,;
                            .F.,;
                            nil,;
                            nil;
                            );
                        )
                        if (lHasError)
                            cError:=EvalBlockGetValue("ErrorDescription","")
                            cError+=EvalBlockGetValue("ErrorStack","")
                            DelSection("EvalBlock")
                            if (!empty(cError))
                                cTLogDetail:=cTools():StrReplace(cError,{CRLF," "})
                                cError:=""
                                cTLogGroup:="table : ["+cSourceFile+"] foram Encontradas inconsistencias na linha ["+cTools():NToS(nft_fRecNo)+"]:"
                                oTLogReport:AddGroup(cTLogGroup)
                                oTLogReport:AddDetail(cTLogGroup,cTLogDetail,nMLCountSize)
                                cTLogDetail:=""
                            endif
                        else
                            nRecProcCustom--
                        endif
                    else
                        if (!lAddNew)
                            lLock:=MySoftLock(cTargetAlias)
                            if (lLock)
                                lLock:=((cTargetAlias)->(MyRecLock(cTargetAlias,lAddNew)))
                            endif
                        else
                           lLock:=((cTargetAlias)->(MyRecLock(cTargetAlias,lAddNew)))
                        endif
                        if (lLock)
                            for nField:=1 to nFields
                                cField:=aTargetFieldsDef[nField][1]
                                if ((lFound).and.(cField$cIndexKey))
                                    loop
                                endif
                                if ((lAddFieldTmp).and.(aScan(aSourceTmpFldStruct,{|e|(e[DBS_NAME]==cField)})>0))
                                    loop
                                endif
                                if ((!oHMTargetFieldsPos:Get(cField,@nTargetFieldPos)).or.(nTargetFieldPos==0))
                                    loop
                                endif
                                xValue:=(cSourceAlias)->(FieldGet(nTargetFieldPos))
                                if (empty(xValue).and.(!lUpdateEmptyValue))
                                    loop
                                endif
                                if ((lMemoVirutal).and.(oHMMemoVirutal:Get(cField,@bUpdateMemoVirtual)))
                                    (cTargetAlias)->(EvalBlock():EvalBlock(bUpdateMemoVirtual))
                                else
                                    (cTargetAlias)->(FieldPut(nTargetFieldPos,xValue))
                                endif
                            next nField
                            if (lAfterUpdateRecNo)
                                lHasError:=(!EvalBlock():EvalBlock({||(cTargetAlias)->(Eval(bAfterUpdateRecNo,cTargetAlias,RecNo()))},nil,.F.,nil,nil))
                                if (lHasError)
                                    cError:=EvalBlockGetValue("ErrorDescription","")
                                    cError+=EvalBlockGetValue("ErrorStack","")
                                    DelSection("EvalBlock")
                                    if (!empty(cError))
                                        cTLogDetail:=cTools():StrReplace(cError,{CRLF," "})
                                        cError:=""
                                        cTLogGroup:="table : ["+cTargetAlias+"] foram Encontradas inconsistencias na linha ["+cTools():NToS((cTargetAlias)->(recNo()))+"] Processo:["+GetCBSource(bAfterUpdateRecNo)+"]:"
                                        oTLogReport:AddGroup(cTLogGroup)
                                        oTLogReport:AddDetail(cTLogGroup,cTLogDetail,nMLCountSize)
                                        cTLogDetail:=""
                                    endif
                                endif
                            endif
                            (cTargetAlias)->(msUnLock())
                        endif
                    endif
                end sequence

                while (nRecProcCustom>=1)

                    nRecProcCustom--

                    nRecProc++
                    if (lPercentage)
                        nRecProcPerc:=(nRecProc*nIncProcStep)
                    else
                        nRecProcPerc:=nRecProc
                    endif

                    oTimeRemaining:nProgress:=nRecProc

                    if ((if(lPercentage,(oHMIncProcStep:Get(nRecProc)),(Mod(nRecProcPerc,nIncProcStep)==0))).or.(nRecProcPerc>=nRecCount))
                        oTimeRemaining:Calcule(.F.)
                        cTimeRemaining:=" :: End of processing in ["+oTimeRemaining:GetcTRemaining()+"]["+DtoC(oTimeRemaining:GetdEndTime())+"]"
                        cTimeRemaining+="["+oTimeRemaining:GetcEndTime()+"]"
                        cTimeRemaining+="["+oTimeRemaining:GetcAverageTime()+"]"
                        cIncProc:="["+oProgress:Eval()+"] "
                        cIncProc+="Updating Record: "
                        cIncProc+=cTools():NToS(nRecProc)
                        cIncProc+="/"
                        cIncProc+=cRecCount
                        cIncProc+=cTimeRemaining
                        cIncProc+="::["+cTools():NToS(if((nRecProcPerc>=nRecCount),100,((nRecProc/nRecCountProc)*100)))+"%]"
                        oMsNewProcess:IncRegua2(cIncProc)
                    endif

                    lEnd:=oMsNewProcess:lEnd

                    if (lEnd)
                        cTLogGroup:="Process canceled by user:"
                        oTLogReport:AddGroup(cTLogGroup)
                        cTLogDetail:="Process canceled by user ["+DtoC(Date())+"]["+Time()+"]"
                        oTLogReport:AddDetail(cTLogGroup,cTLogDetail)
                        exit
                    endif

                end while

                lEnd:=oMsNewProcess:lEnd

                if (lEnd)
                    cTLogGroup:="Process canceled by user:"
                    oTLogReport:AddGroup(cTLogGroup)
                    cTLogDetail:="Process canceled by user ["+DtoC(Date())+"]["+Time()+"]"
                    oTLogReport:AddDetail(cTLogGroup,cTLogDetail)
                    exit
                endif

                if ((cSourceAlias)->(!dbEval():GoToNextRecNo(@cSourceAlias,@nTmpAliasNextRecNo,@nTmpAliasOrder)))
                    exit
                endif

            end while

            for nField:=1 to nFields
                cField:=aTargetFieldsDef[nField][1]
                DelProperty(cField)
            next nField

            if (lEnd)
                break
            endif

            cTLogGroup:="["+cAlias+"/"+cTableImport+"]"

            cTLogDetail:="Data: ["+DToC(oTimeRemaining:GetdStartTime())+"]"
            cTLogDetail+=" "
            cTLogDetail+="Hora: ["+oTimeRemaining:GetcStartTime()+"]"
            cTLogDetail+=" : "
            cTLogDetail+="Inicio da Atualizacao dos Dados (Protheus)."
            oTLogReport:AddDetail(cTLogGroup,cTLogDetail)

            cTLogDetail:="Data: ["+DToC(oTimeRemaining:GetdEndTime())+"]"
            cTLogDetail+=" "
            cTLogDetail+="Hora: ["+oTimeRemaining:GetcEndTime()+"]"
            cTLogDetail+=" : "
            cTLogDetail+="Termino da Atualizacao dos Dados (Protheus)."
            oTLogReport:AddDetail(cTLogGroup,cTLogDetail)

            cTLogDetail:=oTLogReport:ThinLine()
            oTLogReport:AddDetail(cTLogGroup,cTLogDetail)

            cTLogDetail:="["+oTimeRemaining:GetcTimeDiff()+"]"
            cTLogDetail+=" : "
            cTLogDetail+="Tempo de Processamento Atualizacao dos Dados (Protheus)."
            oTLogReport:AddDetail(cTLogGroup,cTLogDetail)

            cTLogDetail:="Hora: ["+oTimeRemaining:GetcAverageTime()+"]"
            cTLogDetail+=" : "
            cTLogDetail+="Tempo Medio de Processamento Atualizacao dos Dados (Protheus)."
            oTLogReport:AddDetail(cTLogGroup,cTLogDetail)

            cTLogDetail:=oTLogReport:ThinLine()
            oTLogReport:AddDetail(cTLogGroup,cTLogDetail)

            if (valType(bAfterUpdateTable)=="B")

                cTime:=Time()

                cTLogGroup:="["+cAlias+"/"+cTableImport+"]"

                cTLogDetail:="Data: ["+DToC(Date())+"]"
                cTLogDetail+=" "
                cTLogDetail+="Hora: ["+Time()+"]"
                cTLogDetail+=" : "
                cTLogDetail+="Inicio das Atualizacoes Complementares (bAfterUpdateTable)."
                oTLogReport:AddDetail(cTLogGroup,cTLogDetail)

                (cTargetAlias)->(dbGoTop())
                lHasError:=(!EvalBlock():EvalBlock(;
                    {||;
                        (cTargetAlias)->(;
                            Eval(;
                                bAfterUpdateTable,;
                                cTargetAlias,;
                                oTLogReport,;
                                oMsNewProcess,;
                                oTimeRemaining,;
                                oProgress;
                            );
                        );
                    },;
                    nil,;
                    .F.,;
                    nil,;
                    nil;
                    );
                )
                if (lHasError)
                    cError:=EvalBlockGetValue("ErrorDescription","")
                    cError+=EvalBlockGetValue("ErrorStack","")
                    DelSection("EvalBlock")
                    if (!empty(cError))
                        cTLogDetail:=cTools():StrReplace(cError,{CRLF," "})
                        cError:=""
                        cTLogGroup:="table : ["+cAlias+"] foram Encontradas inconsistencias no Processo: ["+GetCBSource(bAfterUpdateTable)+"]:"
                        oTLogReport:AddGroup(cTLogGroup)
                        oTLogReport:AddDetail(cTLogGroup,cTLogDetail,nMLCountSize)
                        cTLogDetail:=""
                    endif
                endif

                cTLogGroup:="["+cAlias+"/"+cTableImport+"]"

                cTLogDetail:="Data: ["+DToC(Date())+"]"
                cTLogDetail+=" "
                cTLogDetail+="Hora: ["+Time()+"]"
                cTLogDetail+=" : "
                cTLogDetail+="Termino das Atualizacoes Complementares (bAfterUpdateTable)."
                cTLogDetail+=" : "
                cTLogDetail+="Decorridos: ["+ElapTime(cTime,Time())+"]"
                oTLogReport:AddDetail(cTLogGroup,cTLogDetail)

                cTLogDetail:=oTLogReport:ThinLine()
                oTLogReport:AddDetail(cTLogGroup,cTLogDetail)

            endif

        end sequence

        if (!lPreLoadTable)
            (cSourceAlias)->(dbCloseArea())
            oFWTemporaryTable:Delete()
            oFWTemporaryTable:=FreeObj(oFWTemporaryTable)
        endif

    end sequence

    SetFilAnt(cSVFilAnt)

    DelSection("EvalBlock")

    oProgress:=FreeObj(oProgress)
    oTimeRemaining:=FreeObj(oTimeRemaining)

    if (valType(oFT)=="O")
        oFT:ft_fUse()
        oFT:FreeObj()
        oFT:=FreeObj(oFT)
    endif

    if (Type("oPVTHMSR8Seq")=="O")
        oPVTHMSR8Seq:Clean()
        oPVTHMSR8Seq:=FreeObj(oPVTHMSR8Seq)
    endif

    if (Type("oPVTHMSRDSeq")=="O")
        oPVTHMSRDSeq:Clean()
        oPVTHMSRDSeq:=FreeObj(oPVTHMSRDSeq)
    endif

    if (type("oPVTHMFindSRVPD")=="O")
        oPVTHMFindSRVPD:Clean()
        oPVTHMFindSRVPD:=FreeObj(oPVTHMFindSRVPD)
    endif

    if (valtype(oHMSourceFieldsDef)=="O")
        oHMSourceFieldsDef:Clean()
        oHMSourceFieldsDef:=FreeObj(oHMSourceFieldsDef)
    endif

    if (valtype(oHMTargetFieldsDef)=="O")
        oHMTargetFieldsDef:Clean()
        oHMTargetFieldsDef:=FreeObj(oHMTargetFieldsDef)
    endif

    if (valtype(oHMTargetFieldsPos)=="O")
        oHMTargetFieldsPos:Clean()
        oHMTargetFieldsPos:=FreeObj(oHMTargetFieldsPos)
    endif

    if (lMemoVirutal)
        if (valtype(oHMMemoVirutal)=="O")
            oHMMemoVirutal:Clean()
            oHMMemoVirutal:=FreeObj(oHMMemoVirutal)
        endif
    endif

    if (lPercentage)
        if (valtype(oHMIncProcStep)=="O")
            oHMIncProcStep:Clean()
            oHMIncProcStep:=FreeObj(oHMIncProcStep)
        endif
    endif

    if (lTypeReplicate)
        FWFreeArray(@aTargetReplicateFields)
        FWFreeArray(@aTargetReplicateFieldsPos)
        if (valtype(oHMTargetReplicateFields)=="O")
            oHMTargetReplicateFields:Clean()
            oHMTargetReplicateFields:=FreeObj(oHMTargetReplicateFields)
        endif
    endif

    FWFreeArray(@aLine)
    FWFreeArray(@aField)
    FWFreeArray(@aIncProcStep)

    FWFreeArray(@aFieldsDef)
    FWFreeArray(@aSourceTmpFields)
    FWFreeArray(@aSourceTmpFldStruct)

    FWFreeArray(@aTargetStruct)
    FWFreeArray(@aTargetFieldsDef)
    FWFreeArray(@aReplicateValues)
    FWFreeArray(@aNoReplicateValues)
    FWFreeArray(@aTargetFieldsDefReplicate)

    FWFreeArray(@aUpdateTableFields)
    FWFreeArray(@aUpdateTableSource)

    DelClassIntF()

return(lImportData)

static function readIniFile(cINIFile as character) as logical

    local cRootPath as character

    local cSPPDrive as character
    local cSPPPath as character
    local cSPPFile as character
    local cSPPExt as character

    local lreadIniFile:=.F. as logical

    local oTFIni as object

    begin sequence

        lreadIniFile:=(!empty(cINIFile).and.(File(cINIFile)))
        if (!lreadIniFile)
            ApMsgAlert("Configuration file invalid or not found","Attention")
            break
        endif

        SplitPath(cINIFile,@cSPPDrive,@cSPPPath,@cSPPFile,@cSPPExt)

        cRootPath:=cSPPDrive
        cRootPath+=cSPPPath

        SetValue("cINIFile",cINIFile)
        SetValue("cRootPath",cRootPath)

        oTFIni:=TFIni():New(cINIFile,"#")

        SetValue("readIniFile",oTFIni)

    end sequence

return(lreadIniFile)

static function readTableDefinition() as logical

    local aFieldDef as array
    local aFieldDefTmp as array
    local aFieldsDef:=array(0) as array
    local aTablesImport as array

    local cLine as character
    local cLineUTF8 as character

    local cTable as character
    local cRootPath as character
    local cTablesDefinition as character
    local cFileTablesDefinition as character

    local lTypeReplicate:=.F. as logical
    local lSkipTable:=.F. as logical
    local lreadTableDefinition:=.F. as logical

    local nField as numeric
    local nFields as numeric

    local nft_fRecNo as numeric
    local nft_fHandle as numeric

    local nTypeReplicate as numeric

    local oFT as object
    local oTFIni as object
    local oHMTablesImport as object

    begin sequence

        oTFIni:=GetValue("readIniFile")

        aTablesImport:=aClone(oTFIni:GetAllProperties("TablesImport"))
        lreadTableDefinition:=(!empty(aTablesImport))
        if (!lreadTableDefinition)
            ApMsgAlert("Invalid import tables","Attention")
            break
        endif

        cTablesDefinition:=allTrim(oTFIni:GetPropertyValue("Tables","TablesDefinition",""))
        lreadTableDefinition:=(!empty(cTablesDefinition))
        if (!lreadTableDefinition)
            ApMsgAlert("Invalid TablesDefinition","Attention")
            break
        endif

        cRootPath:=GetValue("cRootPath")
        cFileTablesDefinition:=(cRootPath+".."+cTablesDefinition)
        lreadTableDefinition:=file(cFileTablesDefinition)
        if (!lreadTableDefinition)
            ApMsgAlert("File ("+cFileTablesDefinition+") with the definitions of the tables not found","Attention")
            break
        endif

        oFT:=uft():New()

        MsProcess():MsProcTxt(cFileTablesDefinition)

        nft_fHandle:=oFT:ft_fUse(cFileTablesDefinition)
        lreadTableDefinition:=(nft_fHandle>=0)
        if (!lreadTableDefinition)
            oFT:ft_fUse()
            oFT:=FreeObj(oFT)
            ApMsgAlert("Could not open the file: "+cFileTablesDefinition,"Attention")
            break
        endif

        oHMTablesImport:=aToHM(aTablesImport,2)

        oFT:ft_fGoTop()

        while (!oFT:ft_fEof())
            cLine:=oFT:ft_fReadLN()
            begin sequence
                if (empty(cLine))
                    break
                endif
                cTable:=""
                if ("Table:"==Left(cLine,6))
                    cTable:=strTran(cLine,"Table:","")
                    cTable:=allTrim(cTable)
                    MsProcess():MsProcTxt("Wait! Loading ["+cTable+"]")
                    lSkipTable:=(!oHMTablesImport:Get(cTable))
                    if (lSkipTable)
                        break
                    else
                        oFT:ft_fDelete()
                        oFT:ft_fSkip()
                    endif
                    aSize(aFieldsDef,0)
                    while (!oFT:ft_fEof())
                        MsProcess():MsProcTxt("Wait! Loading ["+cTable+"]")
                        cLine:=oFT:ft_fReadLN()
                        if (empty(cLine).or.("Field Name"==Left(cLine,10)).or.("-"==Left(cLine,1)))
                            oFT:ft_fDelete()
                            oFT:ft_fSkip()
                            loop
                        endif
                        if ("Table:"==Left(cLine,6))
                            SetValue(cTable,aClone(aFieldsDef))
                            aSize(aFieldsDef,0)
                            nft_fRecNo:=oFT:ft_fRecNo()
                            oFT:ft_fGoTo(nft_fRecNo-1)
                            break
                        endif
                        cLine:=cTools():StrReplace(cLine,{"  "," "})
                        cLineUTF8:=DecodeUTF8(cLine)
                        if (empty(cLineUTF8))
                            cLine:=OemToAnsi(cLine)
                        else
                            cLine:=cLineUTF8
                        endif
                        cLineUTF8:=""
                        aFieldDef:=strTokArr2(cLine," ")
                        cLine:=""
                        if (len(aFieldDef)!=DTS_DBS_ALEN)
                            aFieldDefTmp:=array(DTS_DBS_ALEN)
                            aFieldDefTmp[DTS_DBS_NAME]:=aFieldDef[DTS_DBS_NAME]
                            aFieldDefTmp[DTS_DBS_TYPE]:=aFieldDef[DTS_DBS_TYPE]
                            aFieldDefTmp[DTS_DBS_FLG]:=""//DTS_DBS_FLG
                            aFieldDefTmp[DTS_DBS_FORMAT]:=aFieldDef[DTS_DBS_FLG]
                            aFieldDef:=aClone(aFieldDefTmp)
                            FWFreeArray(@aFieldDefTmp)
                        endif
                        nTypeReplicate:=AT("[",aFieldDef[DTS_DBS_TYPE])
                        lTypeReplicate:=(nTypeReplicate>0)
                        if (lTypeReplicate)
                            nFields:=val(subStr(aFieldDef[DTS_DBS_TYPE],(nTypeReplicate+1),(AT("]",aFieldDef[DTS_DBS_TYPE])-1)))
                            aAdd(aFieldsDef,aClone(aFieldDef))
                            if (nFields>1)
                                aFieldDefTmp:=aClone(aFieldDef)
                                SetValue(cTable+"_TypeReplicate",lTypeReplicate)
                                SetValue(aFieldDef[DTS_DBS_NAME]+"_TypeReplicate",nFields)
                                for nField:=2 to nFields
                                    aFieldDef[DTS_DBS_NAME]:=(aFieldDefTmp[DTS_DBS_NAME]+cTools():NToS(nField))
                                    aAdd(aFieldsDef,aClone(aFieldDef))
                                next nField
                                FWFreeArray(@aFieldDefTmp)
                            endif
                        else
                            aAdd(aFieldsDef,aClone(aFieldDef))
                        endif
                        FWFreeArray(@aFieldDef)
                        oFT:ft_fDelete()
                        oFT:ft_fSkip()
                    end while
                    SetValue(cTable,aClone(aFieldsDef))
                    aSize(aFieldsDef,0)
                elseif (lSkipTable)
                    break
                endif
            end sequence
            oFT:ft_fDelete()
            oFT:ft_fSkip()
        end while

    end sequence

    if (valType(oFT)=="O")
        oFT:ft_fUse()
        oFT:FreeObj()
        oFT:=FreeObj(oFT)
    endif

    FWFreeArray(@aFieldsDef)

    if (valtype(oHMTablesImport)=="O")
        oHMTablesImport:Clean()
        oHMTablesImport:=FreeObj(oHMTablesImport)
    endif

    if (valtype(aTablesImport)=="A")
        FWFreeArray(@aTablesImport)
    endif

    DelClassIntF()

return(lreadTableDefinition)

static function getTargetFieldValue(lHasError as logical,oTFIni as object,aLine as array,cTargetField as character,aTargetField as array,aSourceFieldsDef as array,oHMSourceFieldsDef as object,cType as character) as variant

    local aValueField as array
    local aSourceField as array

    local bTransform as codeblock

    local cTransform as character
    local cSourceField as character

    local lSourceTransform as logical

    local nLineSize:=Len(aLine) as numeric
    local nSourceField as numeric
    local nSourceFields as numeric
    local nSourceFieldAT as numeric

    local xValue as variant

    begin sequence

        cSourceField:=aTargetField[2]
        lSourceTransform:=("@"==Left(cSourceField,1))
        if (lSourceTransform)
            cSourceField:=subStr(cSourceField,2)
        endif
        aSourceField:=strToKArr2(cSourceField,"+")
        nSourceFields:=len(aSourceField)
        aValueField:=Array(nSourceFields,2)
        for nSourceField:=1 to nSourceFields
            cSourceField:=aSourceField[nSourceField]
            if (!oHMSourceFieldsDef:Get(cSourceField,@cType))
                loop
            endif
            if (!oHMSourceFieldsDef:Get(cSourceField+"_AT",@nSourceFieldAT))
                loop
            endif
            lHasError:=(nSourceFieldAT>nLineSize)
            if (lHasError)
                break
            endif
            aValueField[nSourceField][1]:=NormalizeData(;
                @lHasError,;
                aLine[nSourceFieldAT],;
                @cType,;
                @cSourceField,;
                @lSourceTransform,;
                @st_oHMbTransform,;
                @oTFIni;
            )
            if (lHasError)
                break
            endif
            aValueField[nSourceField][2]:=cType
            if (cType=="char")
                xValue:=""
            endif
        next nSourceField

        for nSourceField:=1 to nSourceFields
            if (aValueField[nSourceField][2]=="char")
                xValue+=aValueField[nSourceField][1]
            else
                xValue:=aValueField[nSourceField][1]
            endif
        next nSourceField

        if (!st_oHMbTransform:Get(cTargetField,@bTransform))
            cTransform:=allTrim(oTFIni:GetPropertyValue(cTargetField,"Transform",""))
            if (cTransform=="FindInTable")
                cTransform:=allTrim(oTFIni:GetPropertyValue(cTargetField,cTransform,""))
                lHasError:=(!EvalBlock():EvalBlock({||bTransform:=&(cTransform)},nil,.F.,nil,nil))
            elseif (!empty(cTransform))
                lHasError:=(!EvalBlock():EvalBlock({||bTransform:=&(cTransform)},nil,.F.,nil,nil))
            endif
            st_oHMbTransform:Set(cTargetField,bTransform)
        endif

        if (valtype(bTransform)=="B")
            lHasError:=(!EvalBlock():EvalBlock({||xValue:=Eval(bTransform,xValue,@oTFIni,@cType)},nil,.F.,nil,nil))
        endif

    end sequence

    SetValue(cTargetField,xValue)

    FWFreeArray(@aValueField)
    FwFreeArray(@aSourceField)

return(xValue)

static function NormalizeData(lHasError as logical,xValue as variant,cType as character,cSourceField as character,lSourceTransform as logical,st_oHMbTransform as object,oTFIni as object) as variant

    local bTransform as codeblock

    local cTransform as character

    if (lSourceTransform)
        if (!st_oHMbTransform:Get(cSourceField,@bTransform))
            cTransform:=allTrim(oTFIni:GetPropertyValue(cSourceField,"Transform",""))
            if (cTransform=="FindInTable")
                cTransform:=allTrim(oTFIni:GetPropertyValue(cSourceField,cTransform,""))
                lHasError:=(!EvalBlock():EvalBlock({||bTransform:=&(cTransform)},nil,.F.,nil,nil))
            elseif (!empty(cTransform))
                lHasError:=(!EvalBlock():EvalBlock({||bTransform:=&(cTransform)},nil,.F.,nil,nil))
            endif
            if (!lHasError)
                st_oHMbTransform:Set(cSourceField,bTransform)
            endif
        endif
        if (valtype(bTransform)=="B")
            lHasError:=(!EvalBlock():EvalBlock({||xValue:=Eval(bTransform,xValue,oTFIni,@cType)},nil,.F.,nil,nil))
            if (!lHasError)
                xValue:=NormalizeData(@lHasError,xValue,@cType,nil,.F.,nil,nil)
            endif
        endif
    else
        if (valType(xValue)=="C")
            if ("char"$cType)
                xValue:=strTran(xValue,'"',"")
            elseif ("inte"$cType)
                xValue:=Int(val(xValue))
            elseif ("deci"$cType)
                if (","$xValue)
                    xValue:=strTran(xValue,",",".")
                endif
                xValue:=val(xValue)
            elseif ("date"$cType)
                xValue:=CToD(xValue)
            elseif ("logi"$cType)
                xValue:=(Left(lower(xValue),1)$"sty1")
            endif
        endif
    endif

return(xValue)

static function FindInTable(oTFIni as object,cTable as character,xValue as variant,lTableInFile as logical,lUseDFV as logical)

    local cType as character

    local cINIFile as character
    local cRootPath as character

    local oTFIniTable as object

    local xTmp as variant

    cType:=valType(xValue)
    if (cType=="N")
        xValue:=ctools():NToS(xValue)
    elseif (cType!="C")
        xValue:=cValToChar(xValue)
    endif

    if (oTFIni:ExistSection(cTable))
        dfv():Default(@lUseDFV,.T.)
        if (oTFIni:GetATProperty(cTable,"FindInTableFile")>0)
            dfv():Default(@lTableInFile,.F.)
            if (lTableInFile)
                oTFIniTable:=GetValue(cTable,nil)
                if (oTFIniTable==nil)
                    cRootPath:=GetValue("cRootPath")
                    cINIFile:=cRootPath
                    cINIFile+=oTFIni:GetPropertyValue(cTable,"FindInTableFile","")
                    oTFIniTable:=TFIni():New(cINIFile,"#")
                    SetValue(cTable,oTFIniTable)
                endif
                xTmp:=oTFIniTable:GetPropertyValue(cTable,xValue,"")
                if ((lUseDFV).and.(empty(xTmp)).and.((oTFIniTable:GetATProperty(cTable,"__DFV__")>0)))
                    xTmp:=oTFIniTable:GetPropertyValue(cTable,"__DFV__","")
                endif
                xValue:=xTmp
            else
                oTFIniTable:=GetValue(cTable,nil)
                if (oTFIniTable==nil)
                    cRootPath:=GetValue("cRootPath")
                    cINIFile:=cRootPath
                    cINIFile+=oTFIni:GetPropertyValue(cTable,"FindInTableFile","")
                    oTFIniTable:=TFIni():New(cINIFile,"#")
                    SetValue(cTable,oTFIniTable)
                endif
                xValue:=FindInTable(oTFIniTable,cTable,xValue,lTableInFile,lUseDFV)
            endif
        elseif ((oTFIni:GetATProperty(cTable,xValue)>0))
            xValue:=oTFIni:GetPropertyValue(cTable,xValue,"")
        elseif ((lUseDFV).and.(oTFIni:GetATProperty(cTable,"__DFV__")>0))
            xValue:=oTFIni:GetPropertyValue(cTable,"__DFV__","")
        endif
    endif

return(xValue)

static function ProcRedefine(oProcess as object,oTFont as object,nLeft as numeric,nWidth as numeric,nCTLFLeft as numeric,loTDlgF as logical,loTDlgW as logical,lPercentage as logical,lFastMode as logical) as logical
    local lProcRedefine as logical
    lProcRedefine:=MsProcess():ProcRedefine(@oProcess,@oTFont,@nLeft,@nWidth,@nCTLFLeft,@loTDlgF,@loTDlgW,lPercentage,lFastMode)
    return(lProcRedefine)

static function SetFilAnt(cFil as character)
    local cSvFilAnt:=&("cFilAnt") as character
    if (valType("cFilAnt")=="C")
        cSvFilAnt:=&("cFilAnt")
        if (cFil!=cSvFilAnt)
            &("cFilAnt"):=cFil
            FWSM0Util():setSM0PositionBycFilAnt()
        endif
    endif
return(cSvFilAnt)

static procedure CFGFile()

    local cINIFile as character
    local cMemoEdit as character
    local cGetFileRoot as character
    local cGetFileMask as character
    local cGetFileTitle as character

    local lHasINIFile as logical

    local nGetFileOptions as numeric

    local oTFIni as object

    begin sequence

        cGetFileRoot:=GetValue("cRootPath")

        cGetFileMask:=cTools():Accentuation("Arquivo de Configura#1#2o | *.ini","ccedil","atilde")
        cGetFileTitle:=cTools():Accentuation("Arquivo de Configura#1#2o *.ini","ccedil","atilde")
        nGetFileOptions:=(GETF_LOCALHARD+GETF_NETWORKDRIVE)
        cINIFile:=cGetFile(cGetFileMask,cGetFileTitle,1,cGetFileRoot,.F.,nGetFileOptions,/*[lArvore]*/,/*[lKeepCase]*/)

        lHasINIFile:=File(cINIFile)
        if (!lHasINIFile)
            break
        endif

        cMemoEdit:=ReadMemoCFGFile(cINIFile)

        if (EdtCFGFile(@cINIFile,@cMemoEdit))
            if (!("datasul2protheus.ini"$lower(cINIFile)))
                cINIFile:=GetValue("cINIFile")
            endif
            oTFIni:=GetValue("readIniFile")
            if (valType(oTFIni)=="O")
                MsProcess():MsAguarde({||oTFIni:FreeObj()},"Releasing temporary files and workspace memory...","Wait...")
                if (valType(oTFIni)=="O")
                    oTFIni:=FreeObj(oTFIni)
                endif
            endif
            DelSection("datasul2totvsprotheus")
            if (valType(st_oHMbTransform)=="O")
                st_oHMbTransform:Clean()
            endif
            MsProcess():MsAguarde({||datasul2totvs.readIniFile(@cINIFile)},"Loading Settings","Wait! Loading ["+cINIFile+"]")
            MsProcess():MsAguarde({||datasul2totvs.readTableDefinition()},"Loading structure of tables","Wait")
        endif

    end sequence

    return

static function EdtCFGFile(cINIFile as character,cMemoEdit as character) as logical

    local aButtons as array
    local aAdvSize as array
    local aObjSize as array
    local aObjCoords as array
    local aInfoAdvSize as array

    local bSet15 as codeblock
    local bSet24 as codeblock
    local bNotepadCFGFile as codeblock
    local bRestoreCFGFile as codeblock

    local cTitle as character
    local cSVMemoEdit as character

    local lOk as logical

    local nDlgWidth as numeric

    local oTDlg as object
    local oTFont as object
    local oTPanel as object
    local oTMemoEdit as object

    dfv():Default(@cMemoEdit,"")

    cSVMemoEdit:=cMemoEdit

    begin sequence

        aAdvSize:=MsAdvSize()
        aInfoAdvSize:={aAdvSize[1],aAdvSize[2],aAdvSize[3],aAdvSize[4],0,0}
        aObjCoords:=array(0)
        aAdd(aObjCoords,{0,0,.T.,.T.})
        aObjSize:=MsObjSize(aInfoAdvSize,aObjCoords)

        cTitle:="ARQUIVO CONFIGURACAO "
        cTitle+=" :: "
        cTitle+=cINIFile

        DEFINE FONT oTFont NAME "Courier New" SIZE 0,-11 BOLD
        DEFINE MSDIALOG oTDlg TITLE cTitle FROM aAdvSize[7],0 TO aAdvSize[6],aAdvSize[5] OF GetWndDefault() STYLE DS_MODALFRAME STATUS PIXEL

            nDlgWidth:=__DlgWidth(oTDlg)

            oTPanel:=tPanel():New(0,0,"",oTDlg,nil,nil,nil,nil,nil,nDlgWidth,nDlgWidth)

            @(aObjSize[1][1]+5),(aObjSize[1][2]+5) GET oTMemoEdit VAR cMemoEdit MEMO SIZE ((aObjSize[1][4]/100)*99),((aObjSize[1][3]/100)*88) FONT oTFont CENTERED DESIGN OF oTPanel PIXEL WHEN (.T.)

            oTMemoEdit:lReadOnly:=.F.
            oTMemoEdit:EnableVScroll(.T.)
            oTMemoEdit:EnableHScroll(.T.)

            oTDlg:lEscClose:=.F.

            bSet15:={||lOk:=ChgCFGFile(@cINIFile,@cMemoEdit,@cSVMemoEdit),if(lOk,oTDlg:End(),lOK)}
            bSet24:={||lOK:=.F.,oTDlg:End()}

            aButtons:=array(0)
            bNotepadCFGFile:={||MsProcess():MsAguarde({||datasul2totvs.NotepadCFGFile(cINIFile)},"Abrindo no NotepadCFGFile","Aguarde...")}
            aAdd(aButtons,{"NotepadCFGFile",bNotepadCFGFile,OemToAnsi("Abir no NotepadCFGFile"),OemtoAnsi("Abir no NotepadCFGFile")})
            bRestoreCFGFile:={||MsProcess():MsAguarde({||datasul2totvs.RestoreCFGFile(cINIFile,@cMemoEdit,@oTMemoEdit,@cSVMemoEdit)},"Restaurando Versao Anterior","Aguarde...")}
            aAdd(aButtons,{"RestoreCFGFile",bRestoreCFGFile,OemToAnsi("Restaurar Versao Anterior"),OemtoAnsi("Restaurar Versao Anterior")})

        ACTIVATE MSDIALOG oTDlg CENTERED ON INIT EnchoiceBar(oTDlg,bSet15,bSet24,nil,@aButtons)

    end sequence

    return(lOk)

static function ChgCFGFile(cINIFile as character,cMemoEdit as character,cSVMemoEdit as character) as logical

    local cMsg as character
    local cTitle as character

    local cSPDriver as character
    local cSPPath as character
    local cSPFileName as character
    local cSPFileExt as character

    local cFWWSBKP as character

    local lFilial as logical
    local lEmpresa as logical
    local lChgCFGFile as logical

    local nAttemps as numeric

    lFilial:=(type("cFilAnt")=="C")
    lEmpresa:=(type("cEmpAnt")=="C")

    begin sequence

        lChgCFGFile:=(cMemoEdit==cSVMemoEdit)
        if (lChgCFGFile)
            break
        endif

        cSPDriver:=""
        cSPPath:=""
        cSPFileName:=""
        cSPFileExt:=""

        SplitPath(cINIFile,@cSPDriver,@cSPPath,@cSPFileName,@cSPFileExt)

        cMsg:="Deseja Gravar as Alteracoes?"

        cTitle:="ARQUIVO CONFIGURACAO  :: "
        cTitle+=cSPFileName

        lChgCFGFile:=ApMsgYesNo(cMsg,cTitle)
        if (!lChgCFGFile)
            break
        endif

        cFWWSBKP:=cSPDriver
        cFWWSBKP+=cSPPath
        cFWWSBKP+=cSPFileName
        cFWWSBKP+=cSPFileExt
        cFWWSBKP+="-"
        cFWWSBKP+=__cUserID
        cFWWSBKP+="-"
        cFWWSBKP+=DToS(Date())
        cFWWSBKP+="-"
        cFWWSBKP+=strTran(Time(),":","-")
        cFWWSBKP+="-"
        cFWWSBKP+=strZero(ranDomize(1,999),3)

        nAttemps:=0

        cMsg:="O arquivo "
        cMsg+=cINIFile
        cMsg+=" encontra-se em uso deseja tentar novamente?"

        while (!LockByName(cSPFileName,lEmpresa,lFilial,.T.))
            if (nAttemps++>10)
                nAttemps:=0
                if (!MsgYesNo(cMsg,cTitle))
                    lChgCFGFile:=.F.
                    cMsg:="O arquivo "
                    cMsg+=cINIFile
                    cMsg+=" encontra-se em uso e nao podera ser salvo."
                    ApMsgAlert(cMsg,cTitle)
                    break
                endif
            endif
            sleep(300)
        end while

        nAttemps:=0

        while (file(cINIFile))
            if (fRename(cINIFile,cFWWSBKP))
                exit
            endif
            if (nAttemps++>10)
                nAttemps:=0
                if (!MsgYesNo(cMsg,cTitle))
                    UnlockByName(cSPFileName,lEmpresa,lFilial,.T.)
                    lChgCFGFile:=.F.
                    cMsg:="Problema na gravacao do arquivo : "
                    cMsg+=cINIFile
                    ApMsgAlert(cMsg,cTitle)
                    break
                endif
            endif
            sleep(300)
        end while

        nAttemps:=0

        cMsg:="Problema na gravacao do arquivo : "
        cMsg+=cINIFile
        cMsg+=" Deseja tentar novamente?"

        while (!(lChgCFGFile:=MemoWrite(cINIFile,cMemoEdit)))
            if (nAttemps++>10)
                nAttemps:=0
                if (!MsgYesNo(cMsg,cTitle))
                    exit
                endif
            endif
            sleep(300)
        end while

        UnlockByName(cSPFileName,lEmpresa,lFilial,.T.)

        if (!lChgCFGFile)
            cMsg:="Problema na gravacao do arquivo : "
            cMsg+=cINIFile
            ApMsgAlert(cMsg,cTitle)
            break
        endif

        cMsg:="Arquivo "
        cMsg+=cINIFile
        cMsg+=" salvo com sucesso."
        ApMsgInfo(cMsg,cTitle)

    end sequence

    return(lChgCFGFile)

static procedure NotepadCFGFile(cINIFile as character)

    local cSPDriver as character
    local cSPPath as character
    local cSPFileName as character
    local cSPFileExt as character

    local cTempPath as character
    local cTempFile as character

    cSPDriver:=""
    cSPPath:=""
    cSPFileName:=""
    cSPFileExt:=""

    SplitPath(cINIFile,@cSPDriver,@cSPPath,@cSPFileName,@cSPFileExt)

    cTempPath:=getTempPath()
    if (!(right(cTempPath,1)=="\"))
        cTempPath+="\"
    endif

    cTempFile:=cTempPath
    cTempFile+=cSPFileName
    cTempFile+=cSPFileExt

    if (__CopyFile(cINIFile,cTempFile))
        ShellExecute("open",cTempFile,"","",SW_SHOW)
    endif

    return

static function RestoreCFGFile(cINIFile as character,cMemoEdit as character,oTMemoEdit as object,cSVMemoEdit as character) as logical

    local cMask as character
    local cTitle as character
    local cFileRead as character
    local cDirectory as character

    local cSPDriver as character
    local cSPPath as character
    local cSPFileName as character
    local cSPFileExt as character

    local lRestoreCFGFile as logical

    local nOptions as numeric

    begin sequence

        cSPDriver:=""
        cSPPath:=""
        cSPFileName:=""
        cSPFileExt:=""

        SplitPath(cINIFile,@cSPDriver,@cSPPath,@cSPFileName,@cSPFileExt)

        cMask:="Arquivos de Configuracao|"+cSPFileName+"*"
        cTitle:="Restaurar arquivo de Configuracao"
        cDirectory:=cSPDriver
        cDirectory+=cSPPath
        cDirectory:=StrTran(cSPPath,"/","\")
        nOptions:=GETF_NOCHANGEDIR

        cFileRead:=cGetFile(cMask,cTitle,1,cDirectory,.F.,nOptions,/*[lArvore]*/,/*[lKeepCase]*/)

        if (empty(cFileRead))
            break
        endif

        cFileRead:=(cDirectory+cFileRead)
        cFileRead:=StrTran(cFileRead,"\\","\")

        if (!file(cFileRead))
            break
        endif

        cSvMemoEdit:=cMemoEdit
        cMemoEdit:=ReadMemoCFGFile(cFileRead)

        lRestoreCFGFile:=ChgCFGFile(@cINIFile,@cMemoEdit,@cSVMemoEdit)

        if (!lRestoreCFGFile)
            cMemoEdit:=cSvMemoEdit
            break
        endif

        cSvMemoEdit:=cMemoEdit

        oTMemoEdit:Refresh()

    end sequence

    return(lRestoreCFGFile)

static function ReadMemoCFGFile(cFile) as character
    local cMemoRead as character
    cMemoRead:=cTools():ReadMemo(cFile)
    return(cMemoRead)

static function sendDataToServer(cGetFileRoot as character,lReloadConfig as logical) as logical

    local aZipFiles:=array(0) as array

    local aFiles as array
    local aDirectories as array

    local cFile as character
    local cZipFile as character
    local cINIFile as character
    local cDirectory as character
    local cGetFileMask:="" as character
    local cGetFileTitle as character
    local cZipFileServer as character
    local cLowerDirectory as character
    local cDirectoryClient as character
    local cDirectoryServer as character

    local cSPPDrive as character
    local cSPPPath as character
    local cSPPFile as character
    local cSPPExt as character

    local lSendDataToServer as logical

    local nFile as numeric
    local nFiles as numeric
    local nDirectory as numeric
    local nDirectories as numeric
    local nGetFileOptions as numeric

    begin sequence

        lSendDataToServer:=(getComputerName()$(GetNewPar("TOTVSD2PCN","DNA-CSDJ-01")))
        if (!lSendDataToServer)
            break
        endif

        cGetFileTitle:=cTools():Accentuation("Diret#1rio de Configura#2#3o DataSul2Protheus.ini","oacute","ccedil","atilde")
        nGetFileOptions:=(GETF_LOCALHARD+GETF_NETWORKDRIVE+GETF_RETDIRECTORY)
        cDirectoryClient:=cGetFile(cGetFileMask,cGetFileTitle,1,".\",.F.,nGetFileOptions,/*[lArvore]*/,/*[lKeepCase]*/)

        lSendDataToServer:=((lIsDir(cDirectoryClient)).and.("datasul2protheus"$StrTran(lower(cDirectoryClient),"totvs","")))
        if (!lSendDataToServer)
            if (ApMsgYesNo("Invalid directory ["+cDirectoryClient+"]. Want to try again?"))
                lSendDataToServer:=sendDataToServer(@cGetFileRoot)
            elseif (file("\datasul2Protheus\ini\DataSul2Protheus.ini"))
                cGetFileRoot:="SERVIDOR\datasul2protheus\ini\"
            endif
            break
        elseif (file("\datasul2Protheus\ini\DataSul2Protheus.ini"))
            cGetFileRoot:="SERVIDOR\datasul2protheus\ini\"
        endif

        cDirectoryServer:="\datasul2Protheus\"
        DirTools():MakeFileDir(cDirectoryServer)
        lSendDataToServer:=lIsDir(cDirectoryServer)
        if (!lSendDataToServer)
            ApMsgAlert("Invalid directory ["+cDirectoryServer+"]")
            break
        endif

        aDirectories:=Directory(cDirectoryClient+"*.*","D")
        nDirectories:=Len(aDirectories)

        lSendDataToServer:=(nDirectories!=0)
        if (!lSendDataToServer)
            ApMsgAlert("No valid directory information found")
            break
        endif

        for nDirectory:=1 to nDirectories
            if (aDirectories[nDirectory][5]!="D")
                loop
            endif
            cDirectory:=cDirectoryClient
            cDirectory+=aDirectories[nDirectory][1]
            if (right(cDirectory,1)==".")
                loop
            endif
            cLowerDirectory:=lower(cDirectory)
            if (("7z"$cLowerDirectory).or.("src"$cLowerDirectory).or.(".gitignore"$cLowerDirectory).or.(".vscode"$cLowerDirectory))
                loop
            endif
            if (Right(cDirectory,1)!="\")
                cDirectory+="\"
            endif
            aFiles:=Directory(cDirectory+"*.*")
            nFiles:=Len(aFiles)
            for nFile:=1 To nFiles
                cFile:=cDirectory+aFiles[nFile][1]
                MsProcess():MsProcTxt(cFile)
                aAdd(aZipFiles,cFile)
                cFile:=cDirectoryServer+aFiles[nFile][1]
                if (file(cFile))
                    fErase(cFile)
                endif
            next nFile
        next nDirectory

        cZipFile:=(getTempPath()+criatrab(nil,.F.)+".zip")
        MsProcess():MsProcTxt("ZipFile ["+cZipFile+"]. Wait!")
        lSendDataToServer:=(FZip(cZipFile,aZipFiles,cDirectoryClient,/*,[cSenha]*/)==0)
        if (!lSendDataToServer)
            ApMsgAlert("Problem zipping ["+cZipFile+"] file")
            break
        endif

        SplitPath(cZipFile,@cSPPDrive,@cSPPPath,@cSPPFile,@cSPPExt)

        cZipFileServer:=cDirectoryServer
        cZipFileServer+=cSPPFile
        cZipFileServer+=cSPPExt

        MsProcess():MsProcTxt("Wait! Sending ["+cZipFile+"] file to server")
        lSendDataToServer:=__CopyFile(cZipFile,cZipFileServer)
        if (!lSendDataToServer)
            ApMsgAlert("Problem copying ["+cZipFile+"] file to server")
            break
        endif

        MsProcess():MsProcTxt("UnZipFile ["+cZipFileServer+"]. Wait!")
        lSendDataToServer:=(FUnzip(cZipFileServer,cDirectoryServer,/*[cSenha]*/)==0)
        if (!lSendDataToServer)
            ApMsgAlert("Problem unzipping the test ["+cZipFile+"] on the server")
            break
        endif

        cGetFileRoot:="SERVIDOR"+cDirectoryServer

        ApMsgInfo("Files uploaded to the server successfully. Directory ["+cGetFileRoot+"]")

        cGetFileRoot+="ini\"

    end sequence

    FWFreeArray(@aFiles)
    FWFreeArray(@aZipFiles)
    FWFreeArray(@aDirectories)

    if (!empty(cZipFile)).and.(file(cZipFile))
        fErase(cZipFile)
    endif

    if ((!empty(cZipFileServer)).and.(file(cZipFileServer)))
        fErase(cZipFileServer)
    endif

    if (lSendDataToServer)
        dfv():Default(@lReloadConfig,.F.)
        if (lReloadConfig)
            DelSection("datasul2totvsprotheus")
            if (valType(st_oHMbTransform)=="O")
                st_oHMbTransform:Clean()
            endif
            cINIFile:="\datasul2Protheus\ini\DataSul2Protheus.ini"
            MsProcess():MsAguarde({||datasul2totvs.readIniFile(@cINIFile)},"Loading Settings","Wait")
            MsProcess():MsAguarde({||datasul2totvs.readTableDefinition()},"Loading structure of tables","Wait")
        endif
    endif

return(lSendDataToServer)

static function MySoftLock(cAlias as character) as logical
    local lLock as logical
    lLock:=(cAlias)->(MyRecLock(cAlias,.F.,.F.,.T.,.T.))
    return(lLock)

static function MyRecLock(cAlias,lAdd,lDelete,lSoft,lInJob)
    local lLock as logical
    ForceAsBlind(.T.)
        dfv():DefaultEmpty(@lDelete,.F.)
        dfv():DefaultEmpty(@lSoft,.F.)
        dfv():DefaultEmpty(@lInJob:=.T.)
        lLock:=(cAlias)->(RecLock(cAlias,lAdd,lDelete,lSoft,lInJob))
    ForceAsBlind(.F.)
return(lLock)

static function ForceAsBlind(lIsBlind as logical) as logical
    if (valtype(lIsBlind)=="L")
        if (!lIsBlind)
            __cInternet:=nil
            HelpInDark(.F.)
        endif
    else
        lIsBlind:=IsBlind()
        if (!lIsBlind)
            __cInternet:="AUTOMATICO"
            HelpInDark(.T.)
        endif
    endif
return(lIsBlind)

static function GetRecCount(cTable as character, cWhere as character) as numeric
return(dbEval():SQLRecCount(@cTable,@cWhere))

static function TCSQLUpdateTable(;
        cSourceAlias as character,;
        cSourceTable as character,;
        cTargetAlias as character,;
        cTargetTable as character,;
        aTargetFieldsDef as array,;
        aTargetFieldsKeys as array,;
        aSourceTmpFldStruct as array,;
        oMsNewProcess as object,;
        oTLogReport as object,;
        oProgress as object;
    ) as numeric

    local cTime:=Time()
    local cMsProcTXT as character
    local cTLogGroup:=ProcName();
          +" :: ";
          +"["+cSourceTable+"]";
          +" => ";
          +"["+cTargetTable+"]";
          +":" as character
    local cTLogDetail as character

    local bSetRegua:={|nRecCount|;
        cTLogDetail:="Data: ["+DToC(Date())+"]",;
        cTLogDetail+=" ",;
        cTLogDetail+="Hora: ["+cTime+"]",;
        cTLogDetail+=" : ",;
        cTLogDetail+="Inicio do Update de Dados.",;
        oTLogReport:AddDetail(cTLogGroup,cTLogDetail),;
        oMsNewProcess:SetRegua2(nRecCount);
    } as codeblock
    local bIncRegua:={|nMinRecNo,nMaxRecNo,nMinRecNoPlus|;
            cMsProcTXT:="["+oProgress:Eval()+"] ",;
            cMsProcTXT+="Updating records from ",;
            cMsProcTXT+="["+cTools():NToS(nMinRecNo)+"] ",;
            cMsProcTXT+="to ",;
            cMsProcTXT+="["+cTools():NToS(Min(nMaxRecNo,nMinRecNoPlus))+"] ",;
            cMsProcTXT+="out of ",;
            cMsProcTXT+="["+cTools():NToS(nMaxRecNo)+"]",;
            MsProcess():MsProcTxt(cMsProcTXT),;
            oMsNewProcess:IncRegua2(cMsProcTXT);
    } as codeblock
    local bOnError:={|cQueryFull,cSourceTable,cTargetTable,nTCSQLExec,cTCSQLError|;
        cTLogDetail:="TCSQLExec ["+cTools():NToS(nTCSQLExec)+"]",;
        oTLogReport:AddDetail(cTLogGroup,cTLogDetail),;
        cTLogDetail:=cTCSQLError,;
        cTCSQLError:="",;
        oTLogReport:AddDetail(cTLogGroup,cTLogDetail),;
        cTLogDetail:="";
    } as codeblock

    local nTCSQLExec as numeric

    nTCSQLExec:=dbEval():TCSQLUpdateFromTable(;
        @cSourceAlias,;
        @cSourceTable,;
        @cTargetAlias,;
        @cTargetTable,;
        @aTargetFieldsDef,;
        @aTargetFieldsKeys,;
        @aSourceTmpFldStruct,;
        .F./*lSourceKeepRegs*/,;
        @bSetRegua,;
        @bIncRegua,;
        @bOnError;
    )

    cTLogDetail:="Data: ["+DToC(Date())+"]"
    cTLogDetail+=" "
    cTLogDetail+="Hora: ["+Time()+"]"
    cTLogDetail+=" : "
    cTLogDetail+="Termino do Update de Dados."
    cTLogDetail+=" : "
    cTLogDetail+="Decorridos: ["+ElapTime(cTime,Time())+"]"
    oTLogReport:AddDetail(cTLogGroup,cTLogDetail)

return(nTCSQLExec)
